
import { EquipmentStatus, StatusConfig, EquipmentCategory, IsisEntry } from './types';

export const STATUS_CONFIG: Record<EquipmentStatus, StatusConfig> = {
  [EquipmentStatus.IN_LINE]: {
    id: EquipmentStatus.IN_LINE,
    label: "Na Linha",
    color: "#22c55e",
    bgColor: "bg-green-600",
    textColor: "text-white",
    borderColor: "border-green-400"
  },
  [EquipmentStatus.IN_SERVICE]: {
    id: EquipmentStatus.IN_SERVICE,
    label: "De Serviço",
    color: "#3b82f6",
    bgColor: "bg-blue-600",
    textColor: "text-white",
    borderColor: "border-blue-400"
  },
  [EquipmentStatus.RESTRICTED]: {
    id: EquipmentStatus.RESTRICTED,
    label: "Com Restrição",
    color: "#eab308",
    bgColor: "bg-yellow-500",
    textColor: "text-black",
    borderColor: "border-yellow-300"
  },
  [EquipmentStatus.AVAILABLE]: {
    id: EquipmentStatus.AVAILABLE,
    label: "Disponível",
    color: "#94a3b8",
    bgColor: "bg-slate-700",
    textColor: "text-slate-200",
    borderColor: "border-slate-500"
  },
  [EquipmentStatus.UNAVAILABLE]: {
    id: EquipmentStatus.UNAVAILABLE,
    label: "Indisponível",
    color: "#ef4444",
    bgColor: "bg-red-600",
    textColor: "text-white",
    borderColor: "border-red-400"
  }
};

export const CATEGORIES: EquipmentCategory[] = [
  {
    name: "Propulsão e Geração de Energia",
    items: ["MCP BB", "MCP BE", "MCA 1", "MCA 2", "MCA 3", "MCA 4", "Gerador de Emerg"]
  },
  {
    name: "Climatização do AR",
    items: ["URA 1", "URA 2", "URA 3", "URA 4", "URA 5", "URA 6"]
  },
  {
    name: "Osmose e Purificação",
    items: ["GOR 1", "GOR 2", "GOR 3", "GOR 4", "DEMIN", "Separador de Óleo/Água", "Purificador Óleo Comb 1", "Purificador Óleo Comb 2", "Purificador Óleo Lub 1", "Purificador Óleo Lub 2", "Purificador Redutora 1", "Purificador Redutora 2", "Purificador Óleo Lub GER Diesel"]
  },
  {
    name: "Governo (Leme)",
    items: ["Maquina do Leme BE 1", "Maquina do Leme BE 2", "Maquina do Leme BB 1", "Maquina do Leme BB 2"]
  },
  {
    name: "Rede de Incêndio",
    items: ["HPSW 1", "HPSW 2", "HPSW 3", "HPSW 4", "HPSW 5", "Bomba de Serviço 1", "Bomba de Serviço 2", "Bomba de Serviço 3", "MotoBomba 1", "MotoBomba 2", "MotoBomba 3", "MotoBomba 4"]
  },
  {
    name: "Compressores e Bombas de Resfriamento",
    items: ["LPSW 1", "LPSW 2", "LPSW 3", "LPSW 4", "CAP 1", "CAP 2", "CAP 3", "CMP 1", "CMP 2", "CMP de Emergência", "CBP 1", "CBP 2", "CBP 3", "CBP 4", "CBP 5"]
  },
  {
    name: "Planta Frigorífica e Climatização da Água",
    items: ["Planta Frigorífica 1", "Planta Frigorífica 2", "BAG 1", "BAG 2", "BAG 3", "BAG 4", "BOILER 1", "BOILER 2", "BOILER 3", "BOILER 4", "Bomba de Água Quente 1", "Bomba de Água Quente 2", "Container 1", "Container 2", "Container 3"]
  },
  {
    name: "Equipamentos Gerais",
    items: ["Elevador de Aeronaves AV", "Elevador de Aeronaves AR", "Guindaste", "Estabilizador BB", "Estabilizador BE", "Proteção Catódica AV", "Proteção Catódica AR"]
  }
];

export const EQUIPMENT_LOCATIONS: Record<string, string> = {
  "MCP BB": "9L", "MCP BE": "9H", "MCA 1": "9H", "MCA 2": "9H", "MCA 3": "9L", "MCA 4": "9L",
  "Gerador de Emerg": "1K", "URA 1": "9J", "URA 2": "9J", "URA 3": "9J", "URA 4": "9M", "URA 5": "9M", "URA 6": "9M",
  "GOR 1": "9J", "GOR 2": "9J", "GOR 3": "9M", "GOR 4": "9M", "DEMIN": "9K", "Separador de Óleo/Água": "9K",
  "Purificador Óleo Comb 1": "9K", "Purificador Óleo Comb 2": "9K", "Purificador Óleo Lub 1": "9K", "Purificador Óleo Lub 2": "9K",
  "Purificador Redutora 1": "9K", "Purificador Redutora 2": "9K", "Purificador Óleo Lub GER Diesel": "9K",
  "Maquina do Leme BE 1": "7T", "Maquina do Leme BE 2": "7T", "Maquina do Leme BB 1": "7T", "Maquina do Leme BB 2": "7T",
  "HPSW 1": "9D", "HPSW 2": "9F", "HPSW 3": "9H", "HPSW 4": "9L", "HPSW 5": "8Q",
  "Bomba de Serviço 1": "9H", "Bomba de Serviço 2": "9L", "Bomba de Serviço 3": "9L",
  "MotoBomba 1": "7G", "MotoBomba 2": "7J", "MotoBomba 3": "7N", "MotoBomba 4": "7R",
  "LPSW 1": "9H", "LPSW 2": "9H", "LPSW 3": "9L", "LPSW 4": "9L", "CAP 1": "9H", "CAP 2": "9L", "CAP 3": "7C",
  "CMP 1": "9H", "CMP 2": "9L", "CMP de Emergência": "1K", "CBP 1": "9J", "CBP 2": "9J", "CBP 3": "9M", "CBP 4": "9M", "CBP 5": "7P",
  "Planta Frigorífica 1": "7R", "Planta Frigorífica 2": "7R", "BAG 1": "9F", "BAG 2": "9F", "BAG 3": "9N", "BAG 4": "9N",
  "BOILER 1": "9F", "BOILER 2": "9F", "BOILER 3": "9N", "BOILER 4": "9N", "Bomba de Água Quente 1": "9F", "Bomba de Água Quente 2": "9N",
  "Container 1": "4R", "Container 2": "4R", "Container 3": "4R", "Elevador de Aeronaves AV": "1G", "Elevador de Aeronaves AR": "1N",
  "Guindaste": "1P", "Estabilizador BB": "9J", "Estabilizador BE": "9J", "Proteção Catódica AV": "9C", "Proteção Catódica AR": "9N"
};

export const ISIS_DATA: IsisEntry[] = [
  // --- 1.1.XX: FME (MCP AV) ---
  { channel: "1.1.01", description: "FME A BK TC EXH IN", translation: "ENTRADA DA EXAUSTÃO DO TURBO COMPRESSOR DA BANCADA A DO MCP AV" },
  { channel: "1.1.02", description: "FME B BK TC EXH IN", translation: "ENTRADA DA EXAUSTÃO DO TURBO COMPRESSOR DA BANCADA B DO MCP AV" },
  { channel: "1.1.03", description: "FME A BK TC EXH OUT", translation: "SAÍDA DA EXAUSTÃO DO TURBO COMPRESSOR DA BANCADA A DO MCP AV" },
  { channel: "1.1.04", description: "FME B BK TC EXH OUT", translation: "SAÍDA DA EXAUSTÃO DO TURBO COMPRESSOR DA BANCADA B DO MCP AV" },
  { channel: "1.1.05", description: "FME CYL 1A EXH TEMP", translation: "TEMPERATURA DE EXAUSTÃO DO CILINDRO 1 DA BANCADA A DO MCP AV" },
  { channel: "1.1.06", description: "FME CYL 2A EXH TEMP", translation: "TEMPERATURA DE EXAUSTÃO DO CILINDRO 2 DA BANCADA A DO MCP AV" },
  { channel: "1.1.07", description: "FME CYL 3A EXH TEMP", translation: "TEMPERATURA DE EXAUSTÃO DO CILINDRO 3 DA BANCADA A DO MCP AV" },
  { channel: "1.1.08", description: "FME CYL 4A EXH TEMP", translation: "TEMPERATURA DE EXAUSTÃO DO CILINDRO 4 DA BANCADA A DO MCP AV" },
  { channel: "1.1.09", description: "FME CYL 5A EXH TEMP", translation: "TEMPERATURA DE EXAUSTÃO DO CILINDRO 5 DA BANCADA A DO MCP AV" },
  { channel: "1.1.10", description: "FME CYL 6A EXH TEMP", translation: "TEMPERATURA DE EXAUSTÃO DO CILINDRO 6 DA BANCADA A DO MCP AV" },
  { channel: "1.1.11", description: "FME CYL 1B EXH TEMP", translation: "TEMPERATURA DE EXAUSTÃO DO CILINDRO 1 DA BANCADA B DO MCP AV" },
  { channel: "1.1.12", description: "FME CYL 2B EXH TEMP", translation: "TEMPERATURA DE EXAUSTÃO DO CILINDRO 2 DA BANCADA B DO MCP AV" },
  { channel: "1.1.13", description: "FME CYL 3B EXH TEMP", translation: "TEMPERATURA DE EXAUSTÃO DO CILINDRO 3 DA BANCADA B DO MCP AV" },
  { channel: "1.1.14", description: "FME CYL 4B EXH TEMP", translation: "TEMPERATURA DE EXAUSTÃO DO CILINDRO 4 DA BANCADA B DO MCP AV" },
  { channel: "1.1.15", description: "FME CYL 5B EXH TEMP", translation: "TEMPERATURA DE EXAUSTÃO DO CILINDRO 5 DA BANCADA B DO MCP AV" },
  { channel: "1.1.16", description: "FME CYL 6B EXH TEMP", translation: "TEMPERATURA DE EXAUSTÃO DO CILINDRO 6 DA BANCADA B DO MCP AV" },
  { channel: "1.1.17", description: "FME EXH GAS AVERAGE", translation: "VALOR MÉDIO DA TEMPERATURA DA DESCARGA DE GASES DO MCP AV" },
  { channel: "1.1.18", description: "FME EXH DEVIATION", translation: "DESVIO DE DESCARGA DO MCP AV" },
  { channel: "1.1.19", description: "FME CHRG AIR A TEMP", translation: "TEMPERATURA DA DESCARGA DE GASES DA BANCADA A DO MCP AV" },
  { channel: "1.1.20", description: "FME CHRG AIR B TEMP", translation: "TEMPERATURA DA DESCARGA DE GASES DA BANCADA B DO MCP AV" },
  { channel: "1.1.21", description: "FME BRG TEMP HIGH", translation: "ALTA TEMPERATURA DO MANCAL DO MCP AV" },
  { channel: "1.1.22", description: "FME JW OUT TEMP HIGH", translation: "ALTA TEMPERATURA DA SAÍDA DA JAQUETA DE ÁGUA DO MCP AV" },
  { channel: "1.1.23", description: "FME LO IN TEMP HIGH", translation: "ALTA TEMPERATURA NA ENTRADA DO ÓLEO LUBRIFICANTE" },
  { channel: "1.1.24", description: "FME FUEL FILT DIF PR", translation: "PRESSÃO DIFERENCIAL DO FILTRO DE COMBUSTÍVEL DO MCP AV" },
  { channel: "1.1.25", description: "FME LO INLET PRESS", translation: "PRESSÃO DE ENTRADA DO ÓLEO LUBRIFICANTE DO MCP AV" },
  { channel: "1.1.26", description: "FME LO IN TEMP HIGH L", translation: "ALTA TEMPERATURA NA ENTRADA DO ÓLEO LUBRIFICANTE LÓGICO DO MCP AV" },
  { channel: "1.1.27", description: "FME RKR LO PP1 RUN", translation: "BOMBA 1 DE OLEO LUBRIFICANTE DA ROCKER GEAR EM FUNCIONAMENTO DO MCP AV" },
  { channel: "1.1.28", description: "FME RKR LO PP2 RUN", translation: "BOMBA 2 DE OLEO LUBRIFICANTE DA ROCKER GEAR EM FUNCIONAMENTO DO MCP AV" },
  { channel: "1.1.29", description: "FME SHUTDOWN", translation: "DESLIGANDO O MCP AV" },
  { channel: "1.1.30", description: "FME A BK FUEL LEAK", translation: "VAZÃO DE COMBUSTÍVEL DA BANCADA A DO MCP AV" },
  { channel: "1.1.31", description: "FME B BK FUEL LEAK", translation: "VAZÃO DE COMBUSTÍVEL DA BANCADA B DO MCP AV" },
  { channel: "1.1.32", description: "FME CHRG AIR A PRESS", translation: "PRESSÃO DE AR DE CARGA DA BANCADA A DO MCP AV" },
  { channel: "1.1.33", description: "FME CHRG AIR B PRESS", translation: "PRESSÃO DE AR DE CARGA DA BANCADA B DO MCP AV" },
  { channel: "1.1.34", description: "FME OIL MIST DEN HI", translation: "ALTA DENSIDADE DA NÉVOA DE ÓLEO DO MCP AV" },
  { channel: "1.1.35", description: "FME OIL MIST D FAULT", translation: "FALHA NO SENSOR DE DENSIDADE DA NÉVOA DE ÓLEO DO MCP AV" },
  { channel: "1.1.36", description: "FME ENGINE RPM", translation: "RPM DO MCP AV" },
  { channel: "1.1.37", description: "FME SAFTY AIR PR LOW", translation: "BAIXA PRESSÃO NO AR DE SEGURANÇA DO MCP AV" },
  { channel: "1.1.38", description: "FME PROP CTRL SYSTEM", translation: "SISTEMA DE CONTROLE DA PROPULSÃO DO MCP AV" },
  { channel: "1.1.39", description: "FME CHRG AIR TMP", translation: "TEMPERATURA DO AR DE CARGA DO MCP AV" },
  { channel: "1.1.40", description: "FME RKR LO PP1 A-ST", translation: "PARTIDA AUTOMÁTICA DA BOMBA 1 DE ÓLEO LUBRIFICANTE DA ROCKER GEAR DO MCP AV" },
  { channel: "1.1.41", description: "FME RKR LO PP2 A-ST", translation: "PARTIDA AUTOMÁTICA DA BOMBA 2 DE ÓLEO LUBRIFICANTE DA ROCKER GEAR DO MCP AV" },
  { channel: "1.1.42", description: "FME RKR LO LOW PRESS", translation: "BAIXA PRESSÃO DE ÓLEO LUBRIFICANTE DA ROCKER GEAR DO MCP AV" },
  { channel: "1.1.44", description: "FME RKR LO TK LV LOW", translation: "NÍVEL BAIXO DO TANQUE DE ÓLEO LUBRIFICANTE DA ROCKER GEAR DO MCP AV" },
  { channel: "1.1.45", description: "FME RKR LO TK LV HI", translation: "NÍVEL ALTO DO TANQUE DE ÓLEO LUBRIFICANTE DA ROCKER GEAR DO MCP AV" },
  { channel: "1.1.46", description: "FME LO FILT DIF PR", translation: "PRESSÃO DIFERENCIAL DO FILTRO DE ÓLEO LUBRIFICANTE DO MCP AV" },
  { channel: "1.1.47", description: "FME RKR LO FILT DIF", translation: "DIFERENCIAL DO FILTRO DE ÓLEO LUBRIFICANTE DA ROCKER GEAR DO MCP AV" },
  { channel: "1.1.48", description: "SHAFT BRG1 STBD TEMP", translation: "TEMPERATURA DA EIXO DO MANCAL 1 DE BORESTE DO MCP AV" },
  { channel: "1.1.49", description: "FWD LPSW PP1 ASTART", translation: "PARTIDA AUTOMÁTICA DA BOMBA 1 DE RESFRIAMENTO DO MCP AV" },
  { channel: "1.1.50", description: "FWD LPSW PP2 ASTART", translation: "PARTIDA AUTOMÁTICA DA BOMBA 2 DE RESFRIAMENTO DO MCP AV" },
  { channel: "1.1.51", description: "FWD LPSW PRESSURE", translation: "PRESSÃO DA ÁGUA DE RESFRIAMENTO DO MCP AV" },
  { channel: "1.1.52", description: "FWD LPSW TEMERATURE", translation: "TEMPERATURA DA ÁGUA DE ENTRADA DE RESFRIAMENTO DO MCP AV" },
  { channel: "1.1.53", description: "FWD LPSW RECIRC TEMP", translation: "TEMPERATURA DA ÁGUA DE RECIRCULAÇÃO DE RESFRIAMENTO DO MCP AV" },
  { channel: "1.1.54", description: "SEA WATER TEMP", translation: "TEMPERATURA DA ÁGUA DO MAR" },
  { channel: "1.1.55", description: "FME START AIR PR LOW", translation: "BAIXA PRESSÃO DO AR DE PARTIDA DO MCP AV" },
  { channel: "1.1.56", description: "FME T/C RPM A BANK", translation: "RPM DO TURBO COMPRESSOR DA BANCADA A DO MCP AV" },
  { channel: "1.1.57", description: "FME T/C RPM B BANK", translation: "RPM DO TURBO COMPRESSOR DA BANCADA B DO MCP AV" },
  { channel: "1.1.58", description: "FME PROP CTRL SY PWR", translation: "ALIMENTAÇÃO DO SISTEMA DE CONTROLE DA PROPULSÃO DO MCP AV" },
  { channel: "1.1.59", description: "FME OVERSPEED", translation: "EXCESSO DE VELOCIDADE DO MCP AV" },
  { channel: "1.1.60", description: "FME GOV MAJOR ALARM", translation: "MAIOR ALARME DO GOVERNOR DO MCP AV" },
  { channel: "1.1.61", description: "FME GOV MINOR ALARM", translation: "MENOR ALARME DO GOVERNOR DO MCP AV" },
  { channel: "1.1.63", description: "FME GOV ELEC FAIL", translation: "FALHA ELÉTRICA DO GOVERNOR DO MCP AV" },

  // --- 1.2.XX: AUXILIARES AV (Bilge, Fuel, Grey Water) ---
  { channel: "1.2.05", description: "FWD PP ROOM BILGE HI", translation: "BOMBA DE ESGOTO DAS PRAÇAS AV EM FUNCIONAMENTO" },
  { channel: "1.2.06", description: "SFWD SWG RM BILGE HI", translation: "NÍVEL ALTO DO POCETO DE BORESTE DA PMV" },
  { channel: "1.2.07", description: "PFWD SWG RM BILGE HI", translation: "NÍVEL ALTO DO POCETO DE BOMBORDO DA PMV" },
  { channel: "1.2.08", description: "SFWD MAG 9G BILGE HI", translation: "NÍVEL ALTO DO POCETO DE BORESTE DO PAIOL DA 9G" },
  { channel: "1.2.09", description: "PFWD MAG 9G BILGE HI", translation: "NÍVEL ALTO DO POCETO DE BOMBORDO DO PAIOL DA 9G" },
  { channel: "1.2.18", description: "FME FO LEAK TK HIGH", translation: "NÍVEL ALTO DO TANQUE DE GRAVIDADE DE ÓLEO COMBUSTÍVEL DO MCP AV" },
  { channel: "1.2.19", description: "DG1/2 FD LEAK TK HI", translation: "NÍVEL ALTO DO TANQUE DE GRAVIDADE DE ÓLEO COMBUSTÍVEL DG1 E DG2" },
  { channel: "1.2.20", description: "FME FO PUMP1 A/START", translation: "PARTIDA AUTOMÁTICA DA BOMBA 1 DE ÓLEO COMBUSTÍVEL DO MCP AV" },
  { channel: "1.2.21", description: "FME FO PUMP2 A/START", translation: "PARTIDA AUTOMÁTICA DA BOMBA 2 DE ÓLEO COMBUSTÍVEL DO MCP AV" },
  { channel: "1.2.22", description: "FME FO INLET PR LOW", translation: "BAIXA PRESSÃO DA ENTRADA DE COMBUSTÍVEL DO MCP AV" },
  { channel: "1.2.23", description: "FME FO RETURN TEMP", translation: "TEMPERATURA DE RETORNO DO ÓLEO COMBUSTÍVEL DO MCP AV" },
  { channel: "1.2.26", description: "FME JW CIRC PP1 A/ST", translation: "PARTIDA AUTOMÁTICA DA BOMBA 1 DE CIRCULAÇÃO DA ÁGUA DA JAQUETA DO MCP AV" },
  { channel: "1.2.27", description: "FME JW CIRC PP2 A/ST", translation: "PARTIDA AUTOMÁTICA DA BOMBA 2 DE CIRCULAÇÃO DA ÁGUA DA JAQUETA DO MCP AV" },
  { channel: "1.2.28", description: "FME JW PRESS IN LOW", translation: "BAIXA PRESSÃO DA ENTRADA DA ÁGUA DA JAQUETA DO MCP AV" },
  { channel: "1.2.30", description: "FME JW IN TEMP LOW", translation: "BAIXA TEMPERATURA DA ENTRADA DA ÁGUA DA JAQUETA DO MCP AV" },
  { channel: "1.2.32", description: "FME CW DRAIN TK HIGH", translation: "NÍVEL ALTO DO TANQUE DE DRENO DE ÁGUA GELADA DO MCP AV" },
  { channel: "1.2.34", description: "FME EXP TANK LVL LO", translation: "NÍVEL BAIXO DO TANQUE DE EXPANSÃO DO MCP AV" },
  { channel: "1.2.35", description: "DG1 EXP TANK LVL LOW", translation: "NÍVEL BAIXO DO TANQUE DE EXPANSÃO DO DG1" },
  { channel: "1.2.36", description: "DG2 EXP TANK LVL LOW", translation: "NÍVEL BAIXO DO TANQUE DE EXPANSÃO DO DG2" },
  { channel: "1.2.38", description: "SFWD ER BILGE HIGH", translation: "NÍVEL ALTO DO POCETO DE BORESTE DA PMV" },
  { channel: "1.2.39", description: "PFWD ER BILGE HIGH", translation: "NÍVEL ALTO DO POCETO DE BOMBORDO DA PMV" },
  { channel: "1.2.40", description: "9F GREY WATER TNK HI", translation: "NÍVEL ALTO DO TANQUE DE ÁGUAS CINZAS 9F" },
  { channel: "1.2.41", description: "SUBSTATION 2 24 VOLT", translation: "SUBESTAÇÃO 2 24V" },
  { channel: "1.2.46", description: "DG1 FO RETURN TEMP", translation: "TEMPERATURA DE RETORNO DO ÓLEO COMBUSTÍVEL DO DG1" },
  { channel: "1.2.49", description: "DG2 FO RETURN TEMP", translation: "TEMPERATURA DE RETORNO DO ÓLEO COMBUSTÍVEL DO DG2" },
  { channel: "1.2.52", description: "24V SUBSTATION 2GA", translation: "TRU 24V 2GA" },
  { channel: "1.2.57", description: "COLD FW PP.1 PRESS", translation: "PRESSÃO DA BOMBA 1 DE ÁGUA POTÁVEL GELADA" },
  { channel: "1.2.58", description: "COLD FW PP.2 PRESS", translation: "PRESSÃO DA BOMBA 2 DE ÁGUA POTÁVEL GELADA" },
  { channel: "1.2.59", description: "FWD CFW HI PT PRESS", translation: "ALTA PRESSÃO NA PLANTA DE ÁGUA POTÁVEL GELADA AV" },
  { channel: "1.2.60", description: "STBD RO PLANT 1 RUN", translation: "PLANTA 1 DE ÁGUA POTÁVEL DE BORESTE EM FUNCIONAMENTO" },
  { channel: "1.2.61", description: "PORT RO PLANT 2 RUN", translation: "PLANTA 2 DE ÁGUA POTÁVEL DE BORESTE EM FUNCIONAMENTO" },

  // --- 1.3.XX: MCA 1 E 2 (DG1/DG2) ---
  { channel: "1.3.01", description: "DG1 LO PRESS LOW", translation: "BAIXA PRESSÃO DO ÓLEO LUBRIFICANTE DO DG1" },
  { channel: "1.3.02", description: "DG1 LO TEMP HIGH", translation: "ALTA TEMPERATURA DO ÓLEO LUBRIFICANTE DO DG1" },
  { channel: "1.3.03", description: "DG1 JW OUT TEMP HIGH", translation: "ALTA TEMPERATURA NA SAÍDA DA ÁGUA DA JAQUETA DO DG1" },
  { channel: "1.3.04", description: "DG1 JW PRESSURE", translation: "PRESSÃO NA ÁGUA DA JAQUETA DO DG1" },
  { channel: "1.3.05", description: "DG1 CHR AIR A TEMP", translation: "TEMPERATURA DO AR DE CARGA DA BANCADA A DO DG1" },
  { channel: "1.3.06", description: "DG1 CHG AIR B TEMP", translation: "TEMPERATURA DO AR DE CARGA DA BANCADA B DO DG1" },
  { channel: "1.3.07", description: "DG1 FUEL LK HP PIPE", translation: "VAZÃO NA REDE DE COMBUSTÍVEL DA BOMBA DE ALTA PRESSÃO DO DG1" },
  { channel: "1.3.08", description: "DG1 SHUTDOWN", translation: "DESLIGANDO O DG1" },
  { channel: "1.3.09", description: "DG1 FUEL OIL PRESS", translation: "PRESSÃO DE ÓLEO COMBUSTÍVEL DO DG1" },
  { channel: "1.3.10", description: "DG1 JW INLET TEMP", translation: "TEMPERATURA DA ENTRADA DE ÁGUA DA JAQUETA DO DG1" },
  { channel: "1.3.11", description: "DG1 TC EXH GAS OUT T", translation: "SAÍDA DA DESCARGA DE GASES DO TURBO COMPRESSOR DO DG1" },
  { channel: "1.3.12", description: "DG1 RPM", translation: "RPM DO DG1" },
  { channel: "1.3.13", description: "DG1 OIL MIST D FAULT", translation: "FALHA NO SENSOR DE DENSIDADE DA NÉVOA DE ÓLEO DO DG1" },
  { channel: "1.3.14", description: "DG1 DIODE OPEN CRT", translation: "CONTROLE DE ABERTURA DE DIODO DO DG1" },
  { channel: "1.3.15", description: "DG1 U-WIND TEMP HIGH", translation: "ALTA TEMPERATURA DO AR DA FASE U DO DG1" },
  { channel: "1.3.16", description: "DG1 V-WIND TEMP HIGH", translation: "ALTA TEMPERATURA DO AR DA FASE V DO DG1" },
  { channel: "1.3.17", description: "DG1 W-WIND TEMP HIGH", translation: "ALTA TEMPERATURA DO AR DA FASE W DO DG1" },
  { channel: "1.3.18", description: "DG1 END BRG TEMP HI", translation: "ALTA TEMPERATURA NO FINAL DO MANCAL DO DG1" },
  { channel: "1.3.19", description: "DG2 LO PRESS LOW", translation: "BAIXA PRESSÃO DO ÓLEO LUBRIFICANTE DO DG2" },
  { channel: "1.3.20", description: "DG2 LO TEMP HIGH", translation: "ALTA TEMPERATURA DO ÓLEO LUBRIFICANTE DO DG2" },
  { channel: "1.3.21", description: "DG2 JW OUT TEMP HIGH", translation: "ALTA TEMPERATURA NA SAÍDA DA ÁGUA DA JAQUETA DO DG2" },
  { channel: "1.3.22", description: "DG2 JW PRESSURE", translation: "PRESSÃO NA ÁGUA DA JAQUETA DO DG2" },
  { channel: "1.3.23", description: "DG2 CHG AIR A TEMP", translation: "TEMPERATURA DO AR DE CARGA DA BANCADA A DO DG2" },
  { channel: "1.3.24", description: "DG2 CHG AIR B TEMP", translation: "TEMPERATURA DO AR DE CARGA DA BANCADA B DO DG2" },
  { channel: "1.3.25", description: "DG2 FUEL LK HP PIPE", translation: "VAZÃO NA REDE DE COMBUSTÍVEL DA BOMBA DE ALTA PRESSÃO DO DG2" },
  { channel: "1.3.26", description: "DG2 SHUTDOWN", translation: "DESLIGANDO O DG2" },
  { channel: "1.3.27", description: "DG2 FUEL OIL PRESS", translation: "PRESSÃO DE ÓLEO COMBUSTÍVEL DO DG2" },
  { channel: "1.3.28", description: "DG2 JW INLET TEMP", translation: "TEMPERATURA DA ENTRADA DE ÁGUA DA JAQUETA DO DG2" },
  { channel: "1.3.29", description: "DG2 TC EXH GAS OUT T", translation: "SAÍDA DA DESCARGA DE GASES DO TURBO COMPRESSOR DO DG2" },
  { channel: "1.3.30", description: "DG2 RPM", translation: "RPM DO DG2" },
  { channel: "1.3.31", description: "DG2 OIL MIST D FAULT", translation: "FALHA NO SENSOR DE DENSIDADE DA NÉVOA DE ÓLEO DO DG2" },
  { channel: "1.3.32", description: "DG2 DIODE OPEN CCT", translation: "CONTROLE DE ABERTURA DE DIODO DO DG2" },
  { channel: "1.3.33", description: "DG2 U-WIND TEMP HIGH", translation: "ALTA TEMPERATURA DO AR DA FASE U DO DG12" },
  { channel: "1.3.34", description: "DG2 V-WIND TEMP HIGH", translation: "ALTA TEMPERATURA DO AR DA FASE V DO DG2" },
  { channel: "1.3.35", description: "DG2 W-WIND TEMP HIGH", translation: "ALTA TEMPERATURA DO AR DA FASE W DO DG2" },
  { channel: "1.3.36", description: "DG2 END BRG TEMP HI", translation: "ALTA TEMPERATURA NO FINAL DO MANCAL DO DG2" },
  { channel: "1.3.37", description: "DG1 A BNK TC EXH IN", translation: "ENTRADA DA DESCARGA DO TURBO COMPRESSOR DA BANCADA A DO DG1" },
  { channel: "1.3.38", description: "DG1 B BNK TC EXH IN", translation: "ENTRADA DA DESCARGA DO TURBO COMPRESSOR DA BANCADA B DO DG1" },
  { channel: "1.3.39", description: "DG2 A BNK TC EXH IN", translation: "ENTRADA DA DESCARGA DO TURBO COMPRESSOR DA BANCADA A DO DG2" },
  { channel: "1.3.40", description: "DG2 B BNK TC EXH IN", translation: "ENTRADA DA DESCARGA DO TURBO COMPRESSOR DA BANCADA B DO DG2" },
  { channel: "1.3.41", description: "DG1 LO FILT DIF PR", translation: "PRESSÃO DO FILTRO DIFERENCIAL DO ÓLEO LUBRIFICANTE DO DG1" },
  { channel: "1.3.42", description: "DG1 FO FILT DIF PR", translation: "PRESSÃO DO FILTRO DIFERENCIAL DO ÓLEO COMBUSTÍVEL DO DG1" },
  { channel: "1.3.43", description: "DG2 LO FILT DIF PR", translation: "PRESSÃO DO FILTRO DIFERENCIAL DO ÓLEO LUBRIFICANTE DO DG2" },
  { channel: "1.3.44", description: "DG2 FO FILT DIF PR", translation: "PRESSÃO DO FILTRO DIFERENCIAL DO ÓLEO COMBUSTÍVEL DO DG2" },
  { channel: "1.3.45", description: "DG1 DIODE SHORT CRT", translation: "CONTROLE DE CURTO DO DIODO DO DG1" },
  { channel: "1.3.46", description: "DG1 1ST STAGE AL O/P", translation: "PRIMEIRO ESTÁGIO DE ALARME DO DG1" },
  { channel: "1.3.47", description: "DG2 DIODE SHORT CRT", translation: "CONTROLE DE CURTO DO DIODO DO DG2" },
  { channel: "1.3.48", description: "DG2 1ST STAGE AL O/P", translation: "PRIMEIRO ESTÁGIO DE ALARME DO DG2" },
  { channel: "1.3.49", description: "DG1 PMS SYSTEM FAULT", translation: "FALHA NO SISTEMA PMS DO DG1" },
  { channel: "1.3.50", description: "DG2 PMS SYSTEM FAULT", translation: "FALHA NO SISTEMA PMS DO DG2" },
  { channel: "1.3.51", description: "DG1 T/C RPM", translation: "RPM DO TURBO COMPRESSOR DO DG1" },
  { channel: "1.3.52", description: "DG2 T/C RPM", translation: "RPM DO TURBO COMPRESSOR DO DG2" },
  { channel: "1.3.53", description: "DG1 PMS POWER FAIL", translation: "FALHA NA ALIMENTAÇÃO DA PMS DO DG1" },
  { channel: "1.3.54", description: "DG2 PMS POWER FAIL", translation: "FALHA NA ALIMENTAÇÃO DA PMS DO DG2" },

  // --- 1.4.XX: AUXILIARES AV (Compressores, URAs) ---
  { channel: "1.4.02", description: "SWG PLANT1 LVL HIGH", translation: "NÍVEL ALTO DA PLANTA 1 DE DEJETOS" },
  { channel: "1.4.03", description: "SWG PLANT2 LVL HIGH", translation: "NÍVEL ALTO DA PLANTA 2 DE DEJETOS" },
  { channel: "1.4.04", description: "FWD LP PUMP1 RUN", translation: "BOMBA DE BAIXA PRESSÃO DE RESFRIAMENTO 1 AV EM FUNCIONAMENTO" },
  { channel: "1.4.05", description: "FWD LP PUMP2 RUN", translation: "BOMBA DE BAIXA PRESSÃO DE RESFRIAMENTO 2 AV EM FUNCIONAMENTO" },
  { channel: "1.4.06", description: "FME FO PUMP1 RUN", translation: "BOMBA DE ÓLEO COMBUSTÍVEL 1 AV EM FUNCIONAMENTO" },
  { channel: "1.4.07", description: "FME FO PUMP2 RUN", translation: "BOMBA DE ÓLEO COMBUSTÍVEL 2 AV EM FUNCIONAMENTO" },
  { channel: "1.4.08", description: "FME LO PUMP A/START", translation: "PARTIDA AUTOMÁTICA DA BOMBA DE ÓLEO LUBRIFICANTE AV" },
  { channel: "1.4.09", description: "FME LO PUMP1 RUN", translation: "BOMBA DE ÓLEO LUBRIFICANTE 1 AV EM FUNCIONAMENTO" },
  { channel: "1.4.10", description: "FME JW CL PUMP1 RUN", translation: "BOMBA DA ÁGUA DA JAQUETA 1 DO MCP AV EM FUNCIONAMENTO" },
  { channel: "1.4.11", description: "FME JW CL PUMP2 RUN", translation: "BOMBA DA ÁGUA DA JAQUETA 2 DO MCP AV EM FUNCIONAMENTO" },
  { channel: "1.4.12", description: "FME JW WARM PUMP RUN", translation: "BOMBA DE AQUECIMENTO DA ÁGUA DA JAQUETA DO MCP AV EM FUNCIONAMENTO" },
  { channel: "1.4.13", description: "HP AIR COMP1 RUN", translation: "COMPRESSOR DE AR DE ALTA PRESSÃO 1 EM FUNCIONAMENTO" },
  { channel: "1.4.14", description: "HP AIR COMP1 FAULT", translation: "COMPRESSOR DE AR DE ALTA PRESSÃO 1 COM FALHA / DESLIGADO" },
  { channel: "1.4.15", description: "MP AIR COMP1 RUN", translation: "COMPRESSOR DE AR DE MÉDIA PRESSÃO 1 EM FUNCIONAMENTO" },
  { channel: "1.4.16", description: "MP AIR COMP1 FAULT", translation: "COMPRESSOR DE AR DE MÉDIA PRESSÃO 1 COM FALHA / DESLIGADO" },
  { channel: "1.4.17", description: "HP AIR PRESSURE FWD", translation: "PRESSÃO DO AR DE ALTA AV" },
  { channel: "1.4.18", description: "MP AIR FWD PRESS LOW", translation: "PRESSÃO DO AR DE MÉDIA AV" },
  { channel: "1.4.19", description: "CWU SW PP1 DISCH PR", translation: "PRESSÃO DA DESCARGA DA BOMBA DE ÁGUA SALGADA DA URA 1" },
  { channel: "1.4.20", description: "CWU SWPP2 DIS PRESS", translation: "PRESSÃO DA DESCARGA DA BOMBA DE ÁGUA SALGADA DA URA 2" },
  { channel: "1.4.21", description: "CWU SW PP3 DISCH PR", translation: "PRESSÃO DA DESCARGA DA BOMBA DE ÁGUA SALGADA DA URA 3" },
  { channel: "1.4.22", description: "CWU SW PUMP1 RUN", translation: "BOMBA DE ÁGUA SALGADA DA URA 1 EM FUNCIONAMENTO" },
  { channel: "1.4.23", description: "CWU SW PUMP2 RUN", translation: "BOMBA DE ÁGUA SALGADA DA URA 2 EM FUNCIONAMENTO" },
  { channel: "1.4.24", description: "CWU SW PUMP3 RUN", translation: "BOMBA DE ÁGUA SALGADA DA URA 3 EM FUNCIONAMENTO" },
  { channel: "1.4.25", description: "CWU PUMP1 RUN", translation: "BOMBA DE ÁGUA GELADA DA URA 1 EM FUNCIONAMENTO" },
  { channel: "1.4.26", description: "CWU PUMP2 RUN", translation: "BOMBA de ÁGUA GELADA DA URA 2 EM FUNCIONAMENTO" },
  { channel: "1.4.27", description: "CWU PUMP3 RUN", translation: "BOMBA DE ÁGUA GELADA DA URA 3 EM FUNCIONAMENTO" },
  { channel: "1.4.28", description: "CWU COMP 1 RUNNING", translation: "COMPRESSOR DA URA 1 EM FUNCIONAMENTO" },
  { channel: "1.4.29", description: "CWU COMP 2 RUNNING", translation: "COMPRESSOR DA URA 2 EM FUNCIONAMENTO" },
  { channel: "1.4.30", description: "CWU COMP 3 RUNNING", translation: "COMPRESSOR DA URA 3 EM FUNCIONAMENTO" },
  { channel: "1.4.31", description: "CWU NO. 1.2.3. FAULT", translation: "FALHA NAS URAS 1, 2 E 3" },
  { channel: "1.4.32", description: "FIN STAB STBD LCU", translation: "UNIDADE DE CONTROLE LOCAL DA ALHETA DO ESTABILIZADOR DE BORESTE" },
  { channel: "1.4.33", description: "FIN STAB PORT LCU", translation: "UNIDADE DE CONTROLE LOCAL DA ALHETA DO ESTABILIZADOR DE BOMBORDO" },
  { channel: "1.4.34", description: "LP AIR COMP1 RUNNING", translation: "COMPRESSOR DE AR DE BAIXA PRESSÃO 1 EM FUNCIONAMENTO" },
  { channel: "1.4.35", description: "LP AIR COMP1 TRIPPED", translation: "COMPRESSOR DE AR DE BAIXA PRESSÃO 1 COM FALHA / DESLIGADO" },
  { channel: "1.4.36", description: "HYD PK2 RE OP VALVES", translation: "OPERAÇÃO DAS VÁLVULAS DO PACOTE HIDRÁULICO 2 AV" },
  { channel: "1.4.37", description: "HYD PK1 RE OP VALVES", translation: "OPERAÇÃO DAS VÁLVULAS DO PACOTE HIDRÁULICO 1 AV" },
  { channel: "1.4.38", description: "HP AIR COMP3 RUN", translation: "COMPRESSOR DE AR DE ALTA PRESSÃO 3 EM FUNCIONAMENTO" },
  { channel: "1.4.39", description: "HP AIR COMP3 FAULT", translation: "COMPRESSOR DE AR DE ALTA PRESSÃO 3 COM FALHA / DESLIGADO" },
  { channel: "1.4.40", description: "BWTHST FWD BILGE HI", translation: "NÍVEL ALTO DO POCETO DO BOW THRUSTER AV" },
  { channel: "1.4.41", description: "BWTHST AFT BILGE HI", translation: "NÍVEL ALTO DO POCETO DO BOW THRUSTER AR" },
  { channel: "1.4.43", description: "LP AIR FWD PRESS LOW", translation: "PRESSÃO DO AR DE BAIXA AV" },
  { channel: "1.4.44", description: "FME LO DRAIN TK TEMP", translation: "TEMPERATURA DO TANQUE DE DRENO DE ÓLEO LUBRIFICANTE DO MCP AV" },
  { channel: "1.4.45", description: "FME LO WARM PUMP RUN", translation: "BOMBA DE AQUECIMENTO DO ÓLEO LUBRIFICANTE DO MCP AV EM FUNCIONAMENTO" },
  { channel: "1.4.49", description: "FWD DRAUGHT IND", translation: "INDICAÇÃO DO LASTRO AV" },
  { channel: "1.4.50", description: "CWU PUMP1 DISCH PR", translation: "PRESSÃO DE DESCARGA DA BOMBA DA URA 1" },
  { channel: "1.4.51", description: "CWU PUMP2 DISCH PR", translation: "PRESSÃO DE DESCARGA DA BOMBA DA URA 2" },
  { channel: "1.4.52", description: "CWU PUMP3 DISCH PR", translation: "PRESSÃO DE DESCARGA DA BOMBA DA URA 3" },
  { channel: "1.4.53", description: "CWU NO1 TEMP", translation: "TEMPERATURA DA URA 1" },
  { channel: "1.4.54", description: "CWU NO2 TEMP HIGH", translation: "TEMPERATURA DA URA 2" },
  { channel: "1.4.55", description: "CWU NO3 TEMP", translation: "TEMPERATURA DA URA 3" },
  { channel: "1.4.56", description: "FIN STAB BRIDGE EU", translation: "UNIDADE ELETRÔNICA DA ALHETA DO ESTABILIZADOR NO PASSADIÇO" },
  { channel: "1.4.57", description: "LP AIR COMP2 RUNNING", translation: "COMPRESSOR DO AR DE BAIXA PRESSÃO 2 EM FUNCIONAMENTO" },
  { channel: "1.4.58", description: "LP AIR COMP2 TRIPPED", translation: "COMPRESSOR DE AR DE BAIXA PRESSÃO 2 COM FALHA / DESLIGADO" },
  { channel: "1.4.59", description: "SUBSTATION 1 24 VOLT", translation: "SUBESTAÇÃO 1 24V" },
  { channel: "1.4.60", description: "SUBSTATION 4 24 VOLT", translation: "SUBESTAÇÃO 4 24V" },
  { channel: "1.4.61", description: "SUBSTATION 5 24 VOLT", translation: "SUBESTAÇÃO 5 24V" },

  // --- 1.5.XX: REDUTORA 1 E SWITCHBOARDS ---
  { channel: "1.5.02", description: "GB1 HP LO FILT DIF P", translation: "FILTRO DIFERENCIAL DE PRESSÃO DO ÓLEO LUBRIFICANTE DA BOMBA DE ALTA DA REDUTORA 1" },
  { channel: "1.5.03", description: "GB1 LP LO PP1 A/ST", translation: "PARTIDA AUTOMÁTICA DA BOMBA DE BAIXA PRESSÃO 1 DE ÓLEO LUBRIFICANTE DA REDUTORA 1" },
  { channel: "1.5.04", description: "GB1 LP LO PP2 A/ST", translation: "PARTIDA AUTOMÁTICA DA BOMBA DE BAIXA PRESSÃO 2 DE ÓLEO LUBRIFICANTE DA REDUTORA 1" },
  { channel: "1.5.05", description: "GB1 LP LO PP1 RUN", translation: "BOMBA DE BAIXA PRESSÃO 1 DE ÓLEO LUBRIFICANTE DA REDUTORA 1 EM FUNCIONAMENTO" },
  { channel: "1.5.06", description: "GB1 LP LO PP2 RUN", translation: "BOMBA DE BAIXA PRESSÃO 2 DE ÓLEO LUBRIFICANTE DA REDUTORA 1 EM FUNCIONAMENTO" },
  { channel: "1.5.07", description: "GB1 HP LO PP1 A/ST", translation: "PARTIDA AUTOMÁTICA DA BOMBA DE ALTA PRESSÃO 1 DE ÓLEO LUBRIFICANTE DA REDUTORA 1" },
  { channel: "1.5.08", description: "GB1 HP LO PP2 A/ST", translation: "PARTIDA AUTOMÁTICA DA BOMBA DE ALTA PRESSÃO 2 DE ÓLEO LUBRIFICANTE DA REDUTORA 1" },
  { channel: "1.5.09", description: "GB1 HP LO PP1 RUN", translation: "BOMBA DE ALTA PRESSÃO 1 DE ÓLEO LUBRIFICANTE DA REDUTORA 1 EM FUNCIONAMENTO" },
  { channel: "1.5.10", description: "GB1 HPLO PP2 RUN", translation: "BOMBA DE ALTA PRESSÃO 2 DE ÓLEO LUBRIFICANTE DA REDUTORA 1 EM FUNCIONAMENTO" },
  { channel: "1.5.11", description: "GB1 LP LO PRESS LOW", translation: "BAIXA PRESSÃO DE ÓLEO LUBRIFICANTE DA BOMBA DE BAIXA DA REDUTORA 1" },
  { channel: "1.5.12", description: "GB1 HP LO PRESS LO", translation: "BAIXA PRESSÃO DE ÓLEO LUBRIFICANTE DA BOMBA DE ALTA DA REDUTORA 1" },
  { channel: "1.5.13", description: "GB1 LP LO TEMP HIGH", translation: "ALTA TEMPERATURA DE ÓLEO LUBRIFICANTE DA BOMBA DE BAIXA PRESSÃO DA REDUTORA 1" },
  { channel: "1.5.14", description: "GB1 SUMP LEVEL LOW", translation: "NÍVEL BAIXO DO RESERVATÓRIO DA REDUTORA 1" },
  { channel: "1.5.16", description: "GB1FWD PIN BRG TEMP", translation: "TEMPERATURA DO PINO DO MANCAL AV DA REDUTORA 1" },
  { channel: "1.5.17", description: "GB1 AFT GWHEEL BRG T", translation: "TEMPERATURA DO MANCAL INTERNO AR DA REDUTORA 1" },
  { channel: "1.5.18", description: "GB1 FWD GWHEEL BRG T", translation: "TEMPERATURA DO MANCAL INTERNO AV DA REDUTORA 1" },
  { channel: "1.5.19", description: "GB1 THR BRG DRAIN T", translation: "TEMPERATURA DO MANCAL PRÓXIMO AO DRENO DA REDUTORA 1" },
  { channel: "1.5.20", description: "GB1 CLUTCH DRAIN T", translation: "TEMPERATURA DO DRENO DA ENGRENAGEM REDUTORA 1" },
  { channel: "1.5.21", description: "STBD PROP SHAFT RPM", translation: "RPM DO EIXO PROPULSOR DE BORESTE" },
  { channel: "1.5.22", description: "FWD GB RM P BILGE HI", translation: "NÍVEL ALTO DO POCETO DE BOMBORDO DA REDUTORA AV" },
  { channel: "1.5.23", description: "GB1 RECESS BILGE LVL", translation: "NÍVEL DO POCETO DA REDUTORA 1" },
  { channel: "1.5.27", description: "GB1 AFT PIN BRG TEMP", translation: "TEMPERATURA DO PINO DO MANCAL AR DA REDUTORA 1" },
  { channel: "1.5.28", description: "FMSB F1 VOLTS LOW", translation: "BAIXA TENSÃO NO BARRAMENTO F1" },
  { channel: "1.5.29", description: "FMSB F1 VOLTS HIGH", translation: "ALTA TENSÃO NO BARRAMENTO F1" },
  { channel: "1.5.30", description: "FMSB F1 FREQ LOW", translation: "BAIXA FREQUENCIA NO BARRAMENTO F1" },
  { channel: "1.5.31", description: "FMSB F1 FREQ HIGH", translation: "ALTA FREQUENCIA NO BARRAMENTO F1" },
  { channel: "1.5.32", description: "FMSB F1 PREF TRIP PW", translation: "PREFERENCIAL TRIPPED DO BARRAMENTO F1" },
  { channel: "1.5.33", description: "FMSB F1. F2 PREF TRIP", translation: "PREFERENCIAL TRIPPED DO BARRAMENTO F1 E F2" },
  { channel: "1.5.34", description: "FSB SH TRIP PWR FAIL", translation: "FALHA DE ALIMENTAÇÃO DO INTERCONECTOR DO BARRAMENTO AV" },
  { channel: "1.5.35", description: "FWSB F2 VOLTAGE LOW", translation: "BAIXA TENSÃO NO BARRAMENTO F2" },
  { channel: "1.5.36", description: "FMSB F2 VOLTS HIGH", translation: "ALTA TENSÃO NO BARRAMENTO F2" },
  { channel: "1.5.37", description: "FMSB F2 FREQ LOW", translation: "BAIXA FREQUENCIA NO BARRAMENTO F2" },
  { channel: "1.5.38", description: "FMSB F2 FREQ HIGH", translation: "ALTA FREQUENCIA NO BARRAMENTO F2" },
  { channel: "1.5.39", description: "FMSB F2 PREF TRIP PW", translation: "PREFERENCIAL TRIPPED DO BARRAMENTO F2" },
  { channel: "1.5.40", description: "FWD GB RM S BILGE HI", translation: "NÍVEL ALTO DO POCETO DE BORESTE DA REDUTORA 1" },
  { channel: "1.5.42", description: "RO PLANT1 SALINITY H", translation: "NÍVEL ALTO DE SALINIDADE DO GOR 1" },
  { channel: "1.5.43", description: "RO PLANT2 SALINITY H", translation: "NÍVEL ALTO DE SALINIDADE DO GOR 2" },
  { channel: "1.5.44", description: "GB1 QUILL SHFT BRG T", translation: "TEMPERATURA DO MANCAL DO EIXO DA REDUTORA 1" },
  { channel: "1.5.45", description: "GB1 CLUTCH DRAIN OP", translation: "SAÍDA DO DRENO DA ENGRENAGEM REDUTORA 1" },
  { channel: "1.5.46", description: "GB1 CLTCH EN/DISENG", translation: "ENGRAZAMENTO / DESENGRAZAMENTO DA ENGRENAGEM REDUTORA 1" },
  { channel: "1.5.47", description: "GB1 T-GEAR EN/DISENG", translation: "ENGRENAGEM GIRATÓRIA / DESENGRAZAMENTO DA ENGRENAGEM REDUTORA 1" },
  { channel: "1.5.48", description: "GB1 SHFT BRK ON-OFF", translation: "INDICAÇÃO DO FREIO DO EIXO LIGADO / DESLIGADO DA ENGRENAGEM REDUTORA 1" },
  { channel: "1.5.49", description: "GB1 SHFT LOCK ON.OFF", translation: "TRAVAMENTO DO EIXO LIGADO / DESLIGADO DA ENGRENAGEM REDUTORA 1" },
  { channel: "1.5.50", description: "FMSB F1 REVERSE PWR", translation: "POTENCIA REVERSA NO BARRAMENTO F1" },
  { channel: "1.5.51", description: "FMSB F1 OVERCURRENT", translation: "ALTA CORRENTE NO BARRAMENTO F1" },
  { channel: "1.5.52", description: "FMSB F1 SHORT CIRC", translation: "CURTO CIRCUITO NO BARRAMENTO F1" },
  { channel: "1.5.53", description: "FMSB F2 REVERSE PWR", translation: "POTENCIA REVERSA NO BARRAMENTO F2" },
  { channel: "1.5.54", description: "FMSB F2 OVERCURRENT", translation: "ALTA CORRENTE NO BARRAMENTO F2" },
  { channel: "1.5.55", description: "FMSB F2 SHORT CIRC", translation: "CURTO CIRCUITO NO BARRAMENTO F2" },
  { channel: "1.5.56", description: "DDUA MAINT WARNING", translation: "AVISO DE MANUTENÇÃO DA DDU A" },
  { channel: "1.5.57", description: "GYRO A / DDUA FAILURE", translation: "FALHA NA DDU A / GIRO A" },
  { channel: "1.5.59", description: "DDU 1 MAINT WARNING", translation: "AVISO DE MANUTENÇÃO DA DDU 1" },
  { channel: "1.5.60", description: "DDU 1 FAILURE", translation: "FALHA NA DDU 1" },
  { channel: "1.5.61", description: "GB1 SHFTBRK PWR FAIL", translation: "FALHA NA ALIMENTAÇÃO DO FREIO DO EIXO DA ENGRENAGEM REDUTORA 1" },
  { channel: "1.5.62", description: "24VDC SUBSTATION 1KX", translation: "TRU 1KX" },
  { channel: "1.5.63", description: "24VDC SUBSTATION 7JZ", translation: "TRU 7JZ" },
  { channel: "1.5.64", description: "24VDC SUBSTATION 7JA", translation: "TRU 7JA" },

  // --- 1.6.XX: PURIFICADORES E DIVERSOS ---
  { channel: "1.6.01", description: "GB1 LO PURIFY FAULT", translation: "FALHA NO PURIFICADOR DE ÓLEO LUBRIFICANTE DA ENGRENAGEM REDUTORA 1" },
  { channel: "1.6.02", description: "GB1 LO PURIFIER RUN", translation: "PURIFICADOR DE ÓLEO LUBRIFICANTE DA ENGRENAGEM REDUTORA 1 EM FUNCIONAMENTO" },
  { channel: "1.6.03", description: "GB2 LO PURIFY FAULT", translation: "FALHA NO PURIFICADOR DE ÓLEO LUBRIFICANTE DA ENGRENAGEM REDUTORA 2" },
  { channel: "1.6.04", description: "GB2 LO PURIFIER RUN", translation: "PURIFICADOR DE ÓLEO LUBRIFICANTE DA ENGRENAGEM REDUTORA 2 EM FUNCIONAMENTO" },
  { channel: "1.6.05", description: "GB PURIFY SLUDGE TK", translation: "TANQUE DE BORRA DO PURIFICADOR DA ENGRENAGEM REDUTORA" },
  { channel: "1.6.10", description: "DG LO PURIFY FAULT", translation: "FALHA NO PURIFICADOR DE ÓLEO LUBRIFICANTE DO DG" },
  { channel: "1.6.11", description: "DG LO PURIFIER RUN", translation: "PURIFICADOR DE ÓLEO LUBRIFICANTE DO DG EM FUNCIONAMENTO" },
  { channel: "1.6.12", description: "ME1 LO PURIFY FAULT", translation: "FALHA NO PURIFICADOR DE ÓLEO LUBRIFICANTE DO MCP 1" },
  { channel: "1.6.13", description: "ME1 LO PURIFIER RUN", translation: "PURIFICADOR DE ÓLEO LUBRIFICANTE DO MCP 1 EM FUNCIONAMENTO" },
  { channel: "1.6.14", description: "ME2 LO PURIFY FAULT", translation: "FALHA NO PURIFICADOR DE ÓLEO LUBRIFICANTE DO MCP 2" },
  { channel: "1.6.15", description: "ME2 LO PURIFIER RUN", translation: "PURIFICADOR DE ÓLEO LUBRIFICANTE DO MCP 2 EM FUNCIONAMENTO" },
  { channel: "1.6.16", description: "ME/DG PURIFY SLDG TK", translation: "TANQUE DE BORRA DO PURIFICADOR DO MCP E DG" },
  { channel: "1.6.17", description: "FO PURIFIER 1 FAULT", translation: "FALHA NO PURIFICADOR 1 DE ÓLEO COMBUSTÍVEL" },
  { channel: "1.6.18", description: "FO PURIFIER 2 FAULT", translation: "FALHA NO PURIFICADOR 2 DE ÓLEO COMBUSTÍVEL" },
  { channel: "1.6.19", description: "FO PURIFY SLUDGE TK", translation: "TANQUE DE BORRA DO PURIFICADOR DO ÓLEO COMBUSTÍVEL" },
  { channel: "1.6.20", description: "SHAFT BRG2 STBD TEMP", translation: "TEMPERATURA DO MANCAL 2 DO EIXO DE BORESTE" },
  { channel: "1.6.21", description: "SHAFT BRG3 STBD TEMP", translation: "TEMPERATURA DO MANCAL 3 DO EIXO DE BORESTE" },
  { channel: "1.6.22", description: "DIESO STRIP TK34 HI", translation: "NÍVEL ALTO NO TANQUE 34" },
  { channel: "1.6.23", description: "OWS NO1 FAULT", translation: "FALHA NO SEPARADOR DE ÁGUA E ÓLEO 1" },
  { channel: "1.6.24", description: "LO VENT-OFLOW TK HI", translation: "NÍVEL ALTO DO TANQUE DE TRANSBORDO DO ÓLEO LUBRIFICANTE" },
  { channel: "1.6.25", description: "OWS NO1 RUN", translation: "SEPARADOR DE ÁGUA E ÓLEO 1 EM FUNCIONAMENTO" },
  { channel: "1.6.27", description: "OWS NO1 HIGH PPM", translation: "NÍVEL ALTO DE PPM DO SEPARADOR DE ÁGUA E ÓLEO 1" },
  { channel: "1.6.28", description: "OIL BILGE WTR TK LOW", translation: "NÍVEL BAIXO DO TANQUE DE BORRA DO SEPARADOR DE ÁGUA E O ÓLEO" },
  { channel: "1.6.29", description: "OILY SLUDGE TK LVL", translation: "NÍVEL DO TANQUE DE BORRA DE ÓLEO" },
  { channel: "1.6.30", description: "BILGE MID AUXRM STBD", translation: "POCETO DE BORESTE DA 9K" },
  { channel: "1.6.31", description: "BILGE MID AUXRM PORT", translation: "POCETO DE BOMBORDO DA 9K" },
  { channel: "1.6.32", description: "SULLAGE PUMP RUN", translation: "BOMBA DO TANQUE DE BORRA EM FUNCIONAMENTO" },
  { channel: "1.6.33", description: "OILY BILGE PUMP1 RUN", translation: "BOMBA DO POCETO 1 EM FUNCIONAMENTO" },
  { channel: "1.6.34", description: "SEWAGE PLANT 3 HIGH", translation: "NÍVEL ALTO DO TANQUE DE DEJETOS 3" },
  { channel: "1.6.35", description: "RO PLANT5 SALINITY H", translation: "NÍVEL ALTO DO TANQUE DE ÁGUAS DESMINERALIZADA" },
  { channel: "1.6.36", description: "EMGSB VOLTS LOW", translation: "BAIXA TENSÃO NO GSB DE EMERGENCIA" },
  { channel: "1.6.37", description: "EMGSB VOLTS HIGH", translation: "ALTA TENSÃO NO GSB DE EMERGENCIA" },
  { channel: "1.6.38", description: "EMGSB FREQ LOW", translation: "BAIXA FRENQUENCIA NO GSB DE EMERGENCIA" },
  { channel: "1.6.39", description: "EMGSB FREQ HIGH", translation: "ALTA FRENQUENCIA NO GSB DE EMERGENCIA" },
  { channel: "1.6.49", description: "MIDSHIP STBD DRAUGHT", translation: "TANQUE DE LASTRO DA 9K BORESTE" },
  { channel: "1.6.50", description: "MIDSHIP PORT DRAUGHT", translation: "TANQUE DE LASTRO DA 9K BOMBORDO" },
  { channel: "1.6.51", description: "CONSOLE PSU FAILED", translation: "FALHA NO CONSOLE DA PSU" },
  { channel: "1.6.52", description: "CONSOLE BATT OP LOW", translation: "BATERIA DESCARREGADA DO CONSOLE DE OPERAÇÃO" },
  { channel: "1.6.53", description: "EMG GEN FAULT", translation: "FALHA NO GERADOR DE EMERGENCIA" },
  { channel: "1.6.54", description: "EMG GEN SHUTDOWN", translation: "GERADOR DE EMERGENCIA DESLIGADO" },
  { channel: "1.6.55", description: "OWS NO2 FAULT", translation: "FALHA NO SEPARADOR DE ÁGUA E ÓLEO 2" },
  { channel: "1.6.56", description: "OWS NO2 RUN", translation: "SEPARADOR DE ÁGUA E ÓLEO 2 EM FUNCIONAMENTO" },
  { channel: "1.6.57", description: "OWS NO2 HIGH PPM", translation: "NÍVEL ALTO DE PPM DO SEPARADOR DE ÁGUA E ÓLEO 2" },
  { channel: "1.6.58", description: "24 VDC SUBSTATION 2KZ", translation: "TRU 2KZ" },
  { channel: "1.6.59", description: "FO PURIFIER 1 RUN", translation: "PURIFICADOR DE ÓLEO COMBUSTÍVEL 1 EM FUNCIONAMENTO" },
  { channel: "1.6.60", description: "FO PURIFIER 2 RUN", translation: "PURIFICADOR DE ÓLEO COMBUSTÍVEL 2 EM FUNCIONAMENTO" },
  { channel: "1.6.61", description: "SUBSTATON 6 24 VOLT", translation: "SUBESTAÇÃO 6 DE 24V" },
  { channel: "1.6.62", description: "RO PLANT 5 RUNNING", translation: "BOMBA DO TANQUE DE ÁGUA DESMINERALIZADA EM FUNCIONAMENTO" },
  { channel: "1.6.63", description: "A-C WASH TK LVL LOW", translation: "NÍVEL BAIXO DO TANQUE DE LAVAGEM" },
  { channel: "1.6.64", description: "MBR COMMON ALARM", translation: "ALARME COMUM DO MBR" },

  // --- 1.7.XX: VÁLVULAS TANQUES E DG DIVERSOS ---
  { channel: "1.7.04", description: "12-TK HI SUC VV OPEN", translation: "ABERTURA DA VÁLVULA SUPERIOR DE SUCÇÃO DO TANQUE 12" },
  { channel: "1.7.05", description: "12-TK HI SUC VV SHUT", translation: "FECHAMENTO DA VÁLVULA SUPERIOR DE SUCÇÃO DO TANQUE 12" },
  { channel: "1.7.06", description: "12-TK LO SUC VV OPEN", translation: "ABERTURA DA VÁLVULA INFERIOR DE SUCÇÃO DO TANQUE 12" },
  { channel: "1.7.07", description: "12-TK LO SUC VV SHUT", translation: "FECHAMENTO DA VÁLVULA INFERIOR DE SUCÇÃO DO TANQUE 12" },
  { channel: "1.7.08", description: "13-TK HI SUC VV OPEN", translation: "ABERTURA DA VÁLVULA SUPERIOR DE SUCÇÃO DO TANQUE 13" },
  { channel: "1.7.09", description: "13-TK HI SUC VV SHUT", translation: "FECHAMENTO DA VÁLVULA SUPERIOR DE SUCÇÃO DO TANQUE 13" },
  { channel: "1.7.10", description: "13-TK LO SUC VV OPEN", translation: "ABERTURA DA VÁLVULA INFERIOR DE SUCÇÃO DO TANQUE 13" },
  { channel: "1.7.11", description: "13-TK LO SUC VV SHUT", translation: "FECHAMENTO DA VÁLVULA INFERIOR DE SUCÇÃO DO TANQUE 13" },
  { channel: "1.7.12", description: "14-TK HI SUC VV OPEN", translation: "ABERTURA DA VÁLVULA SUPERIOR DE SUCÇÃO DO TANQUE 14" },
  { channel: "1.7.13", description: "14-TK HI SUC VV SHUT", translation: "FECHAMENTO DA VÁLVULA SUPERIOR DE SUCÇÃO DO TANQUE 14" },
  { channel: "1.7.14", description: "14-TK LO SUC VV OPEN", translation: "ABERTURA DA VÁLVULA INFERIOR DE SUCÇÃO DO TANQUE 14" },
  { channel: "1.7.15", description: "14-TK LO SUC VV SHUT", translation: "FECHAMENTO DA VÁLVULA INFERIOR DE SUCÇÃO DO TANQUE 14" },
  { channel: "1.7.16", description: "AVCAT T-EMER PP1 RUN", translation: "BOMBA 1 DO TANQUE DE EMERGENCIA DE COMBUSTÍVEL DA AVIAÇÃO EM FUNCIONAMENTO" },
  { channel: "1.7.17", description: "AVCAT T-EMER PP2 RUN", translation: "BOMBA 2 DO TANQUE DE EMERGENCIA DE COMBUSTÍVEL DA AVIAÇÃO EM FUNCIONAMENTO" },
  { channel: "1.7.18", description: "DG1 CYL 1A EXH TEMP", translation: "TEMPERATURA DE DESCARGA DO CILINDRO 1A DO MCA 1" },
  { channel: "1.7.19", description: "DG1 CYL 2A EXH TEMP", translation: "TEMPERATURA DE DESCARGA DO CILINDRO 2A DO MCA 1" },
  { channel: "1.7.20", description: "DG1 CYL 3A EXH TEMP", translation: "TEMPERATURA DE DESCARGA DO CILINDRO 3A DO MCA 1" },
  { channel: "1.7.21", description: "DG1 CYL 4A EXH TEMP", translation: "TEMPERATURA DE DESCARGA DO CILINDRO 4A DO MCA 1" },
  { channel: "1.7.22", description: "DG1 CYL 5A EXH TEMP", translation: "TEMPERATURA DE DESCARGA DO CILINDRO 5A DO MCA 1" },
  { channel: "1.7.23", description: "DG1 CYL 6A EXH TEMP", translation: "TEMPERATURA DE DESCARGA DO CILINDRO 6A DO MCA 1" },
  { channel: "1.7.24", description: "DG1 CYL 1B EXH TEMP", translation: "TEMPERATURA DE DESCARGA DO CILINDRO 1B DO MCA 1" },
  { channel: "1.7.25", description: "DG1 CYL 2B EXH TEMP", translation: "TEMPERATURA DE DESCARGA DO CILINDRO 2B DO MCA 1" },
  { channel: "1.7.26", description: "DG1 CYL 3B EXH TEMP", translation: "TEMPERATURA DE DESCARGA DO CILINDRO 3B DO MCA 1" },
  { channel: "1.7.27", description: "DG1 CYL 4B EXH TEMP", translation: "TEMPERATURA DE DESCARGA DO CILINDRO 4B DO MCA 1" },
  { channel: "1.7.28", description: "DG1 CYL 5B EXH TEMP", translation: "TEMPERATURA DE DESCARGA DO CILINDRO 5B DO MCA 1" },
  { channel: "1.7.29", description: "DG1 CYL 6B EXH TEMP", translation: "TEMPERATURA DE DESCARGA DO CILINDRO 6B DO MCA 1" },
  { channel: "1.7.30", description: "DG1 EXH GAS AVERAGE", translation: "MÉDIA DAS DESCARGAS DOS GASES DO MCA 1" },
  { channel: "1.7.31", description: "DG1 EXH DEVIATION", translation: "DESVIO DA DESCARGA DO MCA 1" },
  { channel: "1.7.32", description: "DG2 CYL 1A EXH TEMP", translation: "TEMPERATURA DE DESCARGA DO CILINDRO 1A DO MCA 2" },
  { channel: "1.7.33", description: "DG2 CYL 2A EXH TEMP", translation: "TEMPERATURA DE DESCARGA DO CILINDRO 2A DO MCA 2" },
  { channel: "1.7.34", description: "DG2 CYL 3A EXH TEMP", translation: "TEMPERATURA DE DESCARGA DO CILINDRO 3A DO MCA 2" },
  { channel: "1.7.35", description: "DG2 CYL 4A EXH TEMP", translation: "TEMPERATURA DE DESCARGA DO CILINDRO 4A DO MCA 2" },
  { channel: "1.7.36", description: "DG2 CYL 5A EXH TEMP", translation: "TEMPERATURA DE DESCARGA DO CILINDRO 5A DO MCA 2" },
  { channel: "1.7.37", description: "DG2 CYL 6A EXH TEMP", translation: "TEMPERATURA DE DESCARGA DO CILINDRO 6A DO MCA 2" },
  { channel: "1.7.38", description: "DG2 CYL 1B EXH TEMP", translation: "TEMPERATURA DE DESCARGA DO CILINDRO 1B DO MCA 2" },
  { channel: "1.7.39", description: "DG2 CYL 2B EXH TEMP", translation: "TEMPERATURA DE DESCARGA DO CILINDRO 2B DO MCA 2" },
  { channel: "1.7.40", description: "DG2 CYL 3B EXH TEMP", translation: "TEMPERATURA DE DESCARGA DO CILINDRO 3B DO MCA 2" },
  { channel: "1.7.41", description: "DG2 CYL 4B EXH TEMP", translation: "TEMPERATURA DE DESCARGA DO CILINDRO 4B DO MCA 2" },
  { channel: "1.7.42", description: "DG2 CYL 5B EXH TEMP", translation: "TEMPERATURA DE DESCARGA DO CILINDRO 5B DO MCA 2" },
  { channel: "1.7.43", description: "DG2 CYL 6B EXH TEMP", translation: "TEMPERATURA DE DESCARGA DO CILINDRO 6B DO MCA 2" },
  { channel: "1.7.44", description: "DG2 EXH GAS AVERAGE", translation: "MÉDIA DAS DESCARGAS DOS GASES DO MCA 2" },
  { channel: "1.7.45", description: "DG2 EXH DEVIATION", translation: "DESVIO DA DESCARGA DO MCA 2" },
  { channel: "1.7.46", description: "OILY BILGE PUMP2 RUN", translation: "BOMBA DO POCETO 2 EM FUNCIONAMENTO" },
  { channel: "1.7.47", description: "FME OIL MIST D DRT 1", translation: "DENSIDADE DA SUJIDADE DA NÉVOA DE ÓLEO 1 DO MCP AV" },
  { channel: "1.7.48", description: "FME OIL MIST D DRT 2", translation: "DENSIDADE DA SUJIDADE DA NÉVOA DE ÓLEO 2 DO MCP AV" },
  { channel: "1.7.49", description: "FME OIL MIST D DRT 3", translation: "DENSIDADE DA SUJIDADE DA NÉVOA DE ÓLEO 3 DO MCP AV" },
  { channel: "1.7.50", description: "FME OIL MIST D DRT 4", translation: "DENSIDADE DA SUJIDADE DA NÉVOA DE ÓLEO 4 DO MCP AV" },
  { channel: "1.7.51", description: "FME OIL MIST D DRT 5", translation: "DENSIDADE DA SUJIDADE DA NÉVOA DE ÓLEO 5 DO MCP AV" },
  { channel: "1.7.52", description: "FME OIL MIST D DRT 6", translation: "DENSIDADE DA SUJIDADE DA NÉVOA DE ÓLEO 6 DO MCP AV" },

  // --- 2.1.XX: MCA 3 E 4 (DG3/DG4) ---
  { channel: "2.1.01", description: "DG3 LO PRESS LOW", translation: "BAIXA PRESSÃO DO ÓLEO LUBRIFICANTE DO DG3" },
  { channel: "2.1.02", description: "DG3 LO TEMP HIGH", translation: "ALTA TEMPERATURA DO ÓLEO LUBRIFICANTE DO DG3" },
  { channel: "2.1.03", description: "DG3 JW OUT TEMP HIGH", translation: "ALTA TEMPERATURA NA SAÍDA DA ÁGUA DA JAQUETA DO DG3" },
  { channel: "2.1.04", description: "DG3 JW PRESSURE", translation: "PRESSÃO NA ÁGUA DA JAQUETA DO DG3" },
  { channel: "2.1.05", description: "DG3 CHG AIR A TEMP", translation: "TEMPERATURA DO AR DE CARGA DA BANCADA A DO DG3" },
  { channel: "2.1.06", description: "DG3 CHG AIR B TEMP", translation: "TEMPERATURA DO AR DE CARGA DA BANCADA B DO DG3" },
  { channel: "2.1.07", description: "DG3 FUEL LK HP PIPE", translation: "VAZÃO NA REDE DE COMBUSTÍVEL DA BOMBA DE ALTA PRESSÃO DO DG3" },
  { channel: "2.1.08", description: "DG3 SHUTDOWN", translation: "DESLIGANDO O DG3" },
  { channel: "2.1.09", description: "DG3 FUEL OIL PRESS", translation: "PRESSÃO DE ÓLEO COMBUSTÍVEL DO DG3" },
  { channel: "2.1.10", description: "DG3 JW INLET TEMP H", translation: "TEMPERATURA DA ENTRADA DE ÁGUA DA JAQUETA DO DG3" },
  { channel: "2.1.11", description: "DG3 TC EXH GAS TEMP", translation: "SAÍDA DA DESCARGA DE GASES DO TURBO COMPRESSOR DO DG3" },
  { channel: "2.1.12", description: "DG3 RPM", translation: "RPM DO DG3" },
  { channel: "2.1.13", description: "DG3 OIL MIST D FAULT", translation: "FALHA NO SENSOR DE DENSIDADE DA NÉVOA DE ÓLEO DO DG3" },
  { channel: "2.1.14", description: "DG3 DIODE OPEN CRT", translation: "CONTROLE DE ABERTURA DE DIODO DO DG3" },
  { channel: "2.1.15", description: "DG3 U-WIND TEMP HIGH", translation: "ALTA TEMPERATURA DO AR DA FASE U DO DG3" },
  { channel: "2.1.16", description: "DG3 V-WIND TEMP HIGH", translation: "ALTA TEMPERATURA DO AR DA FASE V DO DG3" },
  { channel: "2.1.17", description: "DG3 W-WIND TEMP HIGH", translation: "ALTA TEMPERATURA DO AR DA FASE W DO DG3" },
  { channel: "2.1.18", description: "DG3 END BRG TEMP HI", translation: "ALTA TEMPERATURA NO FINAL DO MANCAL DO DG3" },
  { channel: "2.1.19", description: "DG4 LO PRESS LOW", translation: "BAIXA PRESSÃO DO ÓLEO LUBRIFICANTE DO DG4" },
  { channel: "2.1.20", description: "DG4 LO TEMP HIGH", translation: "ALTA TEMPERATURA DO ÓLEO LUBRIFICANTE DO DG4" },
  { channel: "2.1.21", description: "DG4 JW OUT TEMP HIGH", translation: "ALTA TEMPERATURA NA SAÍDA DA ÁGUA DA JAQUETA DO DG4" },
  { channel: "2.1.22", description: "DG4 JW PRESSURE", translation: "PRESSÃO NA ÁGUA DA JAQUETA DO DG4" },
  { channel: "2.1.23", description: "DG4 CHG AIR A TEMP", translation: "TEMPERATURA DO AR DE CARGA DA BANCADA A DO DG4" },
  { channel: "2.1.24", description: "DG4 CHG AIR B TEMP", translation: "TEMPERATURA DO AR DE CARGA DA BANCADA B DO DG4" },
  { channel: "2.1.25", description: "DG4 FUEL LK HP PIPE", translation: "VAZÃO NA REDE DE COMBUSTÍVEL DA BOMBA DE ALTA PRESSÃO DO DG4" },
  { channel: "2.1.26", description: "DG4 SHUTDOWN", translation: "DESLIGANDO O DG4" },
  { channel: "2.1.27", description: "DG4 FUEL OIL PRESS", translation: "PRESSÃO DE ÓLEO COMBUSTÍVEL DO DG4" },
  { channel: "2.1.28", description: "DG4 JW INLET TEMP H", translation: "TEMPERATURA DA ENTRADA DE ÁGUA DA JAQUETA DO DG4" },
  { channel: "2.1.29", description: "DG4 TC EXH GAS TEMP", translation: "SAÍDA DA DESCARGA DE GASES DO TURBO COMPRESSOR DO DG4" },
  { channel: "2.1.30", description: "DG4 RPM", translation: "RPM DO DG4" },
  { channel: "2.1.31", description: "DG4 OIL MIST D FAULT", translation: "FALHA NO SENSOR DE DENSIDADE DA NÉVOA DE ÓLEO DO DG4" },
  { channel: "2.1.32", description: "DG4 DIODE OPEN CRT", translation: "CONTROLE DE ABERTURA DE DIODO DO DG4" },
  { channel: "2.1.33", description: "DG4 U-WIND TEMP HIGH", translation: "ALTA TEMPERATURA DO AR DA FASE U DO DG4" },
  { channel: "2.1.34", description: "DG4 V-WIND TEMP HIGH", translation: "ALTA TEMPERATURA DO AR DA FASE V DO DG4" },
  { channel: "2.1.35", description: "DG4 W-WIND TEMP HIGH", translation: "ALTA TEMPERATURA DO AR DA FASE W DO DG4" },
  { channel: "2.1.36", description: "DG4 END BRG TEMP HI", translation: "ALTA TEMPERATURA NO FINAL DO MANCAL DO DG4" },
  { channel: "2.1.37", description: "DG3 A BNK TC EXH IN", translation: "ENTRADA DA DESCARGA DO TURBO COMPRESSOR DA BANCADA A DO DG3" },
  { channel: "2.1.38", description: "DG3 B BNK TC EXH IN", translation: "ENTRADA DA DESCARGA DO TURBO COMPRESSOR DA BANCADA B DO DG3" },
  { channel: "2.1.39", description: "DG4 A BNK TC EXH IN", translation: "ENTRADA DA DESCARGA DO TURBO COMPRESSOR DA BANCADA A DO DG4" },
  { channel: "2.1.40", description: "DG4 B BNK TC EXH IN", translation: "ENTRADA DA DESCARGA DO TURBO COMPRESSOR DA BANCADA B DO DG4" },
  { channel: "2.1.41", description: "DG3 LO FILT DIF PR", translation: "PRESSÃO DO FILTRO DIFERENCIAL DO ÓLEO LUBRIFICANTE DO DG3" },
  { channel: "2.1.42", description: "DG3 FO FILT DIF PR", translation: "PRESSÃO DO FILTRO DIFERENCIAL DO ÓLEO COMBUSTÍVEL DO DG3" },
  { channel: "2.1.43", description: "DG4 LO FILT DIF PR", translation: "PRESSÃO DO FILTRO DIFERENCIAL DO ÓLEO LUBRIFICANTE DO DG4" },
  { channel: "2.1.44", description: "DG4 FO FILT DIF PR", translation: "PRESSÃO DO FILTRO DIFERENCIAL DO ÓLEO COMBUSTÍVEL DO DG4" },
  { channel: "2.1.45", description: "DG3 DIODE SHORT CRT", translation: "CONTROLE DE CURTO DO DIODO DO DG3" },
  { channel: "2.1.46", description: "DG3 1ST STAGE AL O/P", translation: "PRIMEIRO ESTÁGIO DE ALARME DO DG3" },
  { channel: "2.1.47", description: "DG4 DIODE SHORT CRT", translation: "CONTROLE DE CURTO DO DIODO DO DG4" },
  { channel: "2.1.48", description: "DG4 1ST STAGE AL O/P", translation: "PRIMEIRO ESTÁGIO DE ALARME DO DG4" },
  { channel: "2.1.49", description: "DG3 PMS SYSTEM FAULT", translation: "FALHA NO SISTEMA PMS DO DG3" },
  { channel: "2.1.50", description: "DG4 PMS SYSTEM FAULT", translation: "FALHA NO SISTEMA PMS DO DG4" },
  { channel: "2.1.51", description: "DG3 T/C RPM", translation: "RPM DO TURBO COMPRESSOR DO DG3" },
  { channel: "2.1.52", description: "DG4 T/C RPM", translation: "RPM DO TURBO COMPRESSOR DO DG4" },
  { channel: "2.1.53", description: "DG3 PMS POWER FAIL", translation: "FALHA NA ALIMENTAÇÃO DA PMS DO DG3" },
  { channel: "2.1.54", description: "DG4 PMS POWER FAIL", translation: "FALHA NA ALIMENTAÇÃO DA PMS DO DG4" },

  // --- 2.2.XX: AUXILIARES AR (Fuel, JW, Bilge) ---
  { channel: "2.2.09", description: "AME FO LEAK TK HIGH", translation: "NÍVEL ALTO DO TANQUE DE GRAVIDADE DE ÓLEO COMBUSTÍVEL DO MCP AR" },
  { channel: "2.2.10", description: "DG3/4 FO LEAK TK HI", translation: "NÍVEL ALTO DO TANQUE DE GRAVIDADE DE ÓLEO COMBUSTÍVEL DG3 E DG4" },
  { channel: "2.2.11", description: "AME FO PUMP3 A/START", translation: "PARTIDA AUTOMÁTICA DA BOMBA 3 DE ÓLEO COMBUSTÍVEL DO MCP AR" },
  { channel: "2.2.12", description: "AME FO PUMP4 A/START", translation: "PARTIDA AUTOMÁTICA DA BOMBA 4 DE ÓLEO COMBUSTÍVEL DO MCP AR" },
  { channel: "2.2.13", description: "AME FO PUMP3 RUN", translation: "BOMBA 3 DE ÓLEO COMBUSTÍVEL DO MCP AR EM FUNCIONAMENTO" },
  { channel: "2.2.14", description: "AME FO PUMP4 RUN", translation: "BOMBA 4 DE ÓLEO COMBUSTÍVEL DO MCP AR EM FUNCIONAMENTO" },
  { channel: "2.2.15", description: "AME FO INLET PR LOW", translation: "BAIXA PRESSÃO DA ENTRADA DE COMBUSTÍVEL DO MCP AR" },
  { channel: "2.2.16", description: "AME FO RETURN TEMP", translation: "TEMPERATURA DE RETORNO DO ÓLEO COMBUSTÍVEL DO MCP AR" },
  { channel: "2.2.19", description: "AME JW CIRC PP3 A/ST", translation: "PARTIDA AUTOMÁTICA DA BOMBA 3 DE CIRCULAÇÃO DA ÁGUA DA JAQUETA DO MCP AR" },
  { channel: "2.2.20", description: "AME JW CIRC PP4 A/ST", translation: "PARTIDA AUTOMÁTICA DA BOMBA 4 DE CIRCULAÇÃO DA ÁGUA DA JAQUETA DO MCP AR" },
  { channel: "2.2.21", description: "AME JW INLET PR LOW", translation: "BAIXA PRESSÃO DA ENTRADA DA ÁGUA DA JAQUETA DO MCP AR" },
  { channel: "2.2.23", description: "AME JW IN TEMP LOW", translation: "BAIXA TEMPERATURA DA ENTRADA DA ÁGUA DA JAQUETA DO MCP AR" },
  { channel: "2.2.25", description: "AME CW DRAIN TK HIGH", translation: "NÍVEL ALTO DO TANQUE DE DRENO DE ÁGUA GELADA DO MCP AR" },
  { channel: "2.2.27", description: "AME EXP TANK LVL LOW", translation: "NÍVEL BAIXO DO TANQUE DE EXPANSÃO DO MCP AR" },
  { channel: "2.2.28", description: "DG3 EXP TANK LVL LOW", translation: "NÍVEL BAIXO DO TANQUE DE EXPANSÃO DO DG3" },
  { channel: "2.2.29", description: "DG4 EXP TANK LVL LOW", translation: "NÍVEL BAIXO DO TANQUE DE EXPANSÃO DO DG4" },
  { channel: "2.2.30", description: "AME JW CL PUMP3 RUN", translation: "BOMBA 3 DE CIRCULAÇÃO DA ÁGUA DA JAQUETA DO MCP AR EM FUNCIONAMENTO" },
  { channel: "2.2.31", description: "AFT LPSW PUMP3 RUN", translation: "BOMBA DE BAIXA PRESSÃO DE RESFRIAMENTO 3 AR EM FUNCIONAMENTO" },
  { channel: "2.2.32", description: "AFT LPSW PUMP4 RUN", translation: "BOMBA DE BAIXA PRESSÃO DE RESFRIAMENTO 4 AR EM FUNCIONAMENTO" },
  { channel: "2.2.33", description: "AME LO PUMP A/START", translation: "PARTIDA AUTOMÁTICA DA BOMBA DE ÓLEO LUBRIFICANTE DO MCP AR" },
  { channel: "2.2.34", description: "AME LO PUMP2 RUN", translation: "BOMBA DE ÓLEO LUBRIFICANTE 2 DO MCP AR EM FUNCIONAMENTO" },
  { channel: "2.2.35", description: "AME JW CL PUMP4 RUN", translation: "BOMBA 4 DE CIRCULAÇÃO DA ÁGUA DA JAQUETA DO MCP AR EM FUNCIONAMENTO" },
  { channel: "2.2.36", description: "AME JW WARN PUMP RUN", translation: "BOMBA DE AQUECIMENTO DA ÁGUA DA JAQUETA DO MCP AR EM FUNCIONAMENTO" },
  { channel: "2.2.37", description: "HP AIR COMP2 RUN", translation: "COMPRESSOR DE AR DE ALTA PRESSÃO 2 EM FUNCIONAMENTO" },
  { channel: "2.2.38", description: "HP AIR COMP2 FAULT", translation: "COMPRESSOR DE AR DE ALTA PRESSÃO 2 FALHA / DESLIGADO" },
  { channel: "2.2.39", description: "MP AIR COMP2 FAULT", translation: "COMPRESSOR DE AR DE MÉDIA PRESSÃO 2 EM FUNCIONAMENTO" },
  { channel: "2.2.40", description: "MP AIR COMP2 FAULT", translation: "COMPRESSOR DE AR DE MÉDIA PRESSÃO 2 FALHA / DESLIGADO" },
  { channel: "2.2.41", description: "HP AIR PRESSURE AFT", translation: "PRESSÃO DO AR DE ALTA AR" },
  { channel: "2.2.42", description: "MP AIR AFT PRESS LOW", translation: "PRESSÃO DO AR DE MÉDIA AR" },
  { channel: "2.2.44", description: "AFT ER BILGE STBD HI", translation: "NÍVEL ALTO DO POCETO DE BORESTE DA PMR" },
  { channel: "2.2.45", description: "AFT ER BILGE PORT HI", translation: "NÍVEL ALTO DO POCETO DE BOMBORDO DA PMR" },
  { channel: "2.2.47", description: "AME LO DRAIN TK TEMP", translation: "TEMPERATURA DO TANQUE DE DRENO DE ÓLEO LUBRIFICANTE DO MCP AR" },
  { channel: "2.2.48", description: "AME LO WARN PUMP RUN", translation: "BOMBA DE AQUECIMENTO DO ÓLEO LUBRIFICANTE DO MCP AR EM FUNCIONAMENTO" },
  { channel: "2.2.49", description: "DG3 FO RETURN TEMP", translation: "TEMPERATURA DE RETORNO DO ÓLEO COMBUSTÍVEL DO DG3" },
  { channel: "2.2.52", description: "DG4 FO RETURN TEMP", translation: "TEMPERATURA DE RETORNO DO ÓLEO COMBUSTÍVEL DO DG4" },

  // --- 2.3.XX: AME (MCP AR) ---
  { channel: "2.3.01", description: "AME A BK TC EXH IN", translation: "ENTRADA DA EXAUSTÃO DO TURBO COMPRESSOR DA BANCADA A DO MCP AR" },
  { channel: "2.3.02", description: "AME B BK TC EXH IN", translation: "ENTRADA DA EXAUSTÃO DO TURBO COMPRESSOR DA BANCADA B DO MCP AR" },
  { channel: "2.3.03", description: "AME A BK TC EXH OUT", translation: "SAÍDA DA EXAUSTÃO DO TURBO COMPRESSOR DA BANCADA A DO MCP AR" },
  { channel: "2.3.04", description: "AME B BK TC EXH OUT", translation: "SAÍDA DA EXAUSTÃO DO TURBO COMPRESSOR DA BANCADA B DO MCP AR" },
  { channel: "2.3.05", description: "AME CYL 1A EXH TEMP", translation: "TEMPERATURA DE EXAUSTÃO DO CILINDRO 1 DA BANCADA A DO MCP AR" },
  { channel: "2.3.06", description: "AME CYL 2A EXH TEMP", translation: "TEMPERATURA DE EXAUSTÃO DO CILINDRO 2 DA BANCADA A DO MCP AR" },
  { channel: "2.3.07", description: "AME CYL 3A EXH TEMP", translation: "TEMPERATURA DE EXAUSTÃO DO CILINDRO 3 DA BANCADA A DO MCP AR" },
  { channel: "2.3.08", description: "AME CYL 4A EXH TEMP", translation: "TEMPERATURA DE EXAUSTÃO DO CILINDRO 4 DA BANCADA A DO MCP AR" },
  { channel: "2.3.09", description: "AME CYL 5A EXH TEMP", translation: "TEMPERATURA DE EXAUSTÃO DO CILINDRO 5 DA BANCADA A DO MCP AR" },
  { channel: "2.3.10", description: "AME CYL 6A EXH TEMP", translation: "TEMPERATURA DE EXAUSTÃO DO CILINDRO 6 DA BANCADA A DO MCP AR" },
  { channel: "2.3.11", description: "AME CYL 1B EXH TEMP", translation: "TEMPERATURA DE EXAUSTÃO DO CILINDRO 1 DA BANCADA B DO MCP AR" },
  { channel: "2.3.12", description: "AME CYL 2B EXH TEMP", translation: "TEMPERATURA DE EXAUSTÃO DO CILINDRO 2 DA BANCADA B DO MCP AR" },
  { channel: "2.3.13", description: "AME CYL 3B EXH TEMP", translation: "TEMPERATURA DE EXAUSTÃO DO CILINDRO 3 DA BANCADA B DO MCP AR" },
  { channel: "2.3.14", description: "AME CYL 4B EXH TEMP", translation: "TEMPERATURA DE EXAUSTÃO DO CILINDRO 4 DA BANCADA B DO MCP AR" },
  { channel: "2.3.15", description: "AME CYL 5B EXH TEMP", translation: "TEMPERATURA DE EXAUSTÃO DO CILINDRO 5 DA BANCADA B DO MCP AR" },
  { channel: "2.3.16", description: "AME CYL 6B EXH TEMP", translation: "TEMPERATURA DE EXAUSTÃO DO CILINDRO 6 DA BANCADA B DO MCP AR" },
  { channel: "2.3.17", description: "AME EXH GAS AVERAGE", translation: "VALOR MÉDIO DA TEMPERATURA DA DESCARGA DE GASES DO MCP AR" },
  { channel: "2.3.18", description: "AME EXH DEVIATION", translation: "DESVIO DE DESCARGA DO MCP AR" },
  { channel: "2.3.19", description: "AME CHRG AIR A TEMP", translation: "TEMPERATURA DA DESCARGA DE GASES DA BANCADA A DO MCP AR" },
  { channel: "2.3.20", description: "AME CHRG AIR B TEMP", translation: "TEMPERATURA DA DESCARGA DE GASES DA BANCADA B DO MCP AR" },
  { channel: "2.3.21", description: "AME BRG TEMP HIGH", translation: "ALTA TEMPERATURA DO MANCAL DO MCP AR" },
  { channel: "2.3.22", description: "AME JW OUT TEMP HIGH", translation: "ALTA TEMPERATURA DA SAÍDA DA JAQUETA DE ÁGUA DO MCP AR" },
  { channel: "2.3.23", description: "AME LO IN TEMP HIGH", translation: "ALTA TEMPERATURA NA ENTRADA DO ÓLEO LUBRIFICANTE DO MCP AR" },
  { channel: "2.3.24", description: "AME FUEL FILT DIF PR", translation: "PRESSÃO DIFERENCIAL DO FILTRO DE COMBUSTÍVEL DO MCP AR" },
  { channel: "2.3.25", description: "AME LO INLET PRESS", translation: "PRESSÃO DE ENTRADA DO ÓLEO LUBRIFICANTE DO MCP AR" },
  { channel: "2.3.26", description: "AME LO INLET PRESS L", translation: "ALTA TEMPERATURA NA ENTRADA DO ÓLEO LUBRIFICANTE LÓGICO DO MCP AR" },
  { channel: "2.3.27", description: "AME RKR LO PP1 RUN", translation: "BOMBA 1 DE OLEO LUBRIFICANTE DA ROCKER GEAR EM FUNCIONAMENTO DO MCP AR" },
  { channel: "2.3.28", description: "AME RKR LO PP2 RUN", translation: "BOMBA 2 DE OLEO LUBRIFICANTE DA ROCKER GEAR EM FUNCIONAMENTO DO MCP AR" },
  { channel: "2.3.29", description: "AME SHUTDOWN", translation: "DESLIGANDO O MCP AR" },
  { channel: "2.3.30", description: "AME A BK FUEL LEAK", translation: "VAZAMENTO DE COMBUSTÍVEL DA BANCADA A DO MCP AR" },
  { channel: "2.3.31", description: "AME B BK FUEL LEAK", translation: "VAZAMENTO DE COMBUSTÍVEL DA BANCADA B DO MCP AR" },
  { channel: "2.3.32", description: "AME CHRG AIR A PRESS", translation: "PRESSÃO DE AR DE CARGA DA BANCADA A DO MCP AR" },
  { channel: "2.3.33", description: "AME CHRG AIR B PRESS", translation: "PRESSÃO DE AR DE CARGA DA BANCADA B DO MCP AR" },
  { channel: "2.3.34", description: "AME OIL MIST DEN HI", translation: "ALTA DENSIDADE DA NÉVOA DE ÓLEO DO MCP AR" },
  { channel: "2.3.35", description: "AME OIL MIST D FAULT", translation: "FALHA NO SENSOR DE DENSIDADE DA NÉVOA DE ÓLEO DO MCP AR" },
  { channel: "2.3.36", description: "AFT MAIN ENGINE RPM", translation: "RPM DO MCP AR" },
  { channel: "2.3.37", description: "AME SAFTY AIR PR LOW", translation: "BAIXA PRESSÃO NO AR DE SEGURANÇA DO MCP AR" },
  { channel: "2.3.38", description: "AME PROP CTRL SYSTEM", translation: "SISTEMA DE CONTROLE DA PROPULSÃO DO MCP AR" },
  { channel: "2.3.39", description: "AME CHRG AIR TEMP", translation: "TEMPERATURA DO AR DE CARGA DO MCP AR" },
  { channel: "2.3.40", description: "AME RKR LO PP1 A-ST", translation: "PARTIDA AUTOMÁTICA DA BOMBA 1 DE ÓLEO LUBRIFICANTE DA ROCKER GEAR DO MCP AR" },
  { channel: "2.3.41", description: "AME RKR LO PP2 A-ST", translation: "PARTIDA AUTOMÁTICA DA BOMBA 2 DE ÓLEO LUBRIFICANTE DA ROCKER GEAR DO MCP AR" },
  { channel: "2.3.42", description: "AME RKR LO LOW PRESS", translation: "BAIXA PRESSÃO DE ÓLEO LUBRIFICANTE DA ROCKER GEAR DO MCP AR" },
  { channel: "2.3.44", description: "AME RKR LO TK LV LOW", translation: "NÍVEL BAIXO DO TANQUE DE ÓLEO LUBRIFICANTE DA ROCKER GEAR DO MCP AR" },
  { channel: "2.3.45", description: "AME RKR LO TK LV HI", translation: "NÍVEL ALTO DO TANQUE DE ÓLEO LUBRIFICANTE DA ROCKER GEAR DO MCP AR" },
  { channel: "2.3.46", description: "AME LO FILT DIF PR", translation: "PRESSÃO DIFERENCIAL DO FILTRO DE ÓLEO LUBRIFICANTE DO MCP AR" },
  { channel: "2.3.47", description: "AME RKR LO FILT DIF", translation: "DIFERENCIAL DO FILTRO DE ÓLEO LUBRIFICANTE DA ROCKER GEAR DO MCP AR" },
  { channel: "2.3.48", description: "SHAFT BRG4 STBD TEMP", translation: "TEMPERATURA DA EIXO DO MANCAL 4 DE BORESTE DO MCP AV" },
  { channel: "2.3.50", description: "AFT LPSW PP3 ASTART", translation: "PARTIDA AUTOMÁTICA DA BOMBA 3 DE RESFRIAMENTO DO MCP AR" },
  { channel: "2.3.51", description: "AFT LPSW PP4 ASTART", translation: "PARTIDA AUTOMÁTICA DA BOMBA 4 DE RESFRIAMENTO DO MCP AR" },
  { channel: "2.3.52", description: "AFT LPSW PRESSURE", translation: "PRESSÃO DA ÁGUA DE RESFRIAMENTO DO MCP AR" },
  { channel: "2.3.53", description: "AFT LPSW TEMPERATURE", translation: "TEMPERATURA DA ÁGUA DE ENTRADA DE RESFRIAMENTO DO MCP AR" },
  { channel: "2.3.54", description: "AFT LPSW RECIRC TEMP", translation: "TEMPERATURA DA ÁGUA DE RECIRCULAÇÃO DE RESFRIAMENTO DO MCP AR" },
  { channel: "2.3.55", description: "AME START AIR PR LOW", translation: "BAIXA PRESSÃO DO AR DE PARTIDA DO MCP AR" },
  { channel: "2.3.56", description: "AME T/C RPM A BANK", translation: "RPM DO TURBO COMPRESSOR DA BANCADA A DO MCP AR" },
  { channel: "2.3.57", description: "AME T/C RPM B BANK", translation: "RPM DO TURBO COMPRESSOR DA BANCADA B DO MCP AR" },
  { channel: "2.3.58", description: "AME PROP CTRL SY PWR", translation: "ALIMENTAÇÃO DO SISTEMA DE CONTROLE DA PROPULSÃO DO MCP AR" },
  { channel: "2.3.59", description: "AME OVERSPEED", translation: "EXCESSO DE VELOCIDADE DO MCP AR" },
  { channel: "2.3.60", description: "AME GOV MAJOR ALARM", translation: "MAIOR ALARME DO GOVERNOR DO MCP AR" },
  { channel: "2.3.61", description: "AME GOV MINOR ALARM", translation: "MENOR ALARME DO GOVERNOR DO MCP AR" },
  { channel: "2.3.63", description: "AME GOV ELEC FAIL", translation: "FALHA ELÉTRICA DO GOVERNOR DO MCP AR" },
  { channel: "2.3.64", description: "SHAFT BRG8 PORT TEMP", translation: "TEMPERATURA DA EIXO DO MANCAL 8 DE BOMBORDO DO MCP AV" },

  // --- 2.4.XX: REDUTORA 2 E CWU AR ---
  { channel: "2.4.01", description: "GB2 LP LO FILT DIF P", translation: "FILTRO DIFERENCIAL DE PRESSÃO DO ÓLEO LUBRIFICANTE DA BOMBA DE BAIXA DA REDUTORA 2" },
  { channel: "2.4.02", description: "GB2 HP LO FILT DIF P", translation: "FILTRO DIFERENCIAL DE PRESSÃO DO ÓLEO LUBRIFICANTE DA BOMBA DE ALTA DA REDUTORA 2" },
  { channel: "2.4.03", description: "GB2 LP LO PP3 A/ST", translation: "PARTIDA AUTOMÁTICA DA BOMBA DE BAIXA PRESSÃO 3 DE ÓLEO LUBRIFICANTE DA REDUTORA 2" },
  { channel: "2.4.04", description: "GB2 LP LO PP4 A/ST", translation: "PARTIDA AUTOMÁTICA DA BOMBA DE BAIXA PRESSÃO 4 DE ÓLEO LUBRIFICANTE DA REDUTORA 2" },
  { channel: "2.4.05", description: "GB2 LP LO PP3 RUN", translation: "BOMBA DE BAIXA PRESSÃO 3 DE ÓLEO LUBRIFICANTE DA REDUTORA 1 EM FUNCIONAMENTO" },
  { channel: "2.4.06", description: "GB2 LP LO PP4 RUN", translation: "BOMBA DE BAIXA PRESSÃO 4 DE ÓLEO LUBRIFICANTE DA REDUTORA 1 EM FUNCIONAMENTO" },
  { channel: "2.4.07", description: "GB2 HP LO PP3 A/ST", translation: "PARTIDA AUTOMÁTICA DA BOMBA DE ALTA PRESSÃO 3 DE ÓLEO LUBRIFICANTE DA REDUTORA 2" },
  { channel: "2.4.08", description: "GB2 HP LO PP4 A/ST", translation: "PARTIDA AUTOMÁTICA DA BOMBA DE ALTA PRESSÃO 4 DE ÓLEO LUBRIFICANTE DA REDUTORA 2" },
  { channel: "2.4.09", description: "GB2 HP LO PP3 RUN", translation: "BOMBA DE ALTA PRESSÃO 3 DE ÓLEO LUBRIFICANTE DA REDUTORA 2 EM FUNCIONAMENTO" },
  { channel: "2.4.10", description: "GB2 HP LO PP4 RUN", translation: "BOMBA DE ALTA PRESSÃO 4 DE ÓLEO LUBRIFICANTE DA REDUTORA 2 EM FUNCIONAMENTO" },
  { channel: "2.4.11", description: "GB2 LP LO PRESS LOW", translation: "BAIXA PRESSÃO DE ÓLEO LUBRIFICANTE DA BOMBA DE BAIXA DA REDUTORA 2" },
  { channel: "2.4.12", description: "GB2 HP LO PRESS LOW", translation: "BAIXA PRESSÃO DE ÓLEO LUBRIFICANTE DA BOMBA DE ALTA DA REDUTORA 2" },
  { channel: "2.4.13", description: "GB2 LP LO TEMP HIGH", translation: "ALTA TEMPERATURA DE ÓLEO LUBRIFICANTE DA BOMBA DE BAIXA PRESSÃO DA REDUTORA 2" },
  { channel: "2.4.14", description: "GB2 SUMP LEVEL LOW", translation: "NÍVEL BAIXO DO RESERVATÓRIO DA REDUTORA 2" },
  { channel: "2.4.15", description: "GB2 AFT PIN BRG TEMP", translation: "TEMPERATURA DO PINO DO MANCAL AR DA REDUTORA 2" },
  { channel: "2.4.16", description: "GB2 FWD PIN BRG TEMP", translation: "TEMPERATURA DO PINO DO MANCAL AV DA REDUTORA 2" },
  { channel: "2.4.19", description: "GB2 THR BRG DRAIN T", translation: "TEMPERATURA DO MANCAL INTERNO AR DA REDUTORA 2" },
  { channel: "2.4.20", description: "GB2 CLUTCH DRAIN T", translation: "TEMPERATURA DO MANCAL INTERNO AV DA REDUTORA 2" },
  { channel: "2.4.21", description: "PORT PROP SHAFT RPM", translation: "RPM DO EIXO PROPULSOR DE BOMBORDO" },
  { channel: "2.4.22", description: "PORT PROP SHAFT TORQ", translation: "TORQUE DO EIXO PROPULSOR DE BOMBORDO" },
  { channel: "2.4.23", description: "SHAFT BRG5 STBD TEMP", translation: "TEMPERATURA DO MANCAL 5 DO EIXO BOMBORDO" },
  { channel: "2.4.25", description: "STBD PROP SHAFT TORQ", translation: "TORQUE DO EIXO PROPULSOR DE BORESTE" },
  { channel: "2.4.28", description: "GB2 RECESS BILGE HI", translation: "NÍVEL ALTO DO POCETO DA REDUTORA 2" },
  { channel: "2.4.29", description: "AFT GB RM S BILGE HI", translation: "NÍVEL ALTO DO POCETO DE BORESTE DA REDUTORA AR" },
  { channel: "2.4.30", description: "AFT GB RM P BILGE HI", translation: "NÍVEL ALTO DO POCETO DE BOMBORDO DA REDUTORA AR" },
  { channel: "2.4.31", description: "CWU SW PP4 DISCH PR", translation: "PRESSÃO DA DESCARGA DA BOMBA DE ÁGUA SALGADA DA URA 4" },
  { channel: "2.4.32", description: "CWU SW PP5 DISCH PR", translation: "PRESSÃO DA DESCARGA DA BOMBA DE ÁGUA SALGADA DA URA 5" },
  { channel: "2.4.33", description: "CWU SW PP6 DISCH PR", translation: "PRESSÃO DA DESCARGA DA BOMBA DE ÁGUA SALGADA DA URA 6" },
  { channel: "2.4.34", description: "CWU SW PUMP4 RUN", translation: "BOMBA DE ÁGUA SALGADA DA URA 4 EM FUNCIONAMENTO" },
  { channel: "2.4.35", description: "CWU SW PUMP5 RUN", translation: "BOMBA DE ÁGUA SALGADA DA URA 5 EM FUNCIONAMENTO" },
  { channel: "2.4.36", description: "CWU SW PUMP6 RUN", translation: "BOMBA DE ÁGUA SALGADA DA URA 6 EM FUNCIONAMENTO" },
  { channel: "2.4.37", description: "CWU PUMP4 RUN", translation: "BOMBA DE ÁGUA GELADA DA URA 4 EM FUNCIONAMENTO" },
  { channel: "2.4.38", description: "CWU PUMP5 RUN", translation: "BOMBA DE ÁGUA GELADA DA URA 5 EM FUNCIONAMENTO" },
  { channel: "2.4.39", description: "CWU PUMP6 RUN", translation: "BOMBA DE ÁGUA GELADA DA URA 6 EM FUNCIONAMENTO" },
  { channel: "2.4.40", description: "CWU COMP 4 RUNNING", translation: "COMPRESSOR DA URA 4 EM FUNCIONAMENTO" },
  { channel: "2.4.41", description: "CWU COMP 5 RUNNING", translation: "COMPRESSOR DA URA 5 EM FUNCIONAMENTO" },
  { channel: "2.4.42", description: "CWU COMP 6 RUNNING", translation: "COMPRESSOR DA URA 6 EM FUNCIONAMENTO" },
  { channel: "2.4.43", description: "CWU NO 4.5.6.FAULT", translation: "FALHA NAS URAS 4, 5 E 6" },
  { channel: "2.4.44", description: "STBD RO PLANT 3 RUN", translation: "GOR 3 EM FUNCIONAMENTO" },
  { channel: "2.4.45", description: "PORT RO PLANT 4 RUN", translation: "GOR 4 EM FUNCIONAMENTO" },
  { channel: "2.4.46", description: "SUBSTATION 3 24 VOLT", translation: "SUBESTAÇÃO 3 DE 24V" },
  { channel: "2.4.48", description: "RO PLANT3 SALINITY H", translation: "NÍVEL ALTO DE SALINIDADE DO GOR 3" },
  { channel: "2.4.49", description: "RO PLANT4 SALINITY H", translation: "NÍVEL ALTO DE SALINIDADE DO GOR 4" },
  { channel: "2.4.51", description: "GB2 QUILL SHFT BRG T", translation: "TEMPERATURA DO MANCAL DO EIXO DA REDUTORA 2" },
  { channel: "2.4.52", description: "LP AIR AFT PRESS LOW", translation: "PRESSÃO DO AR DE BAIXA AR" },
  { channel: "2.4.53", description: "GB2 CLUTCH DRAIN O/P", translation: "SAÍDA DO DRENO DA ENGRENAGEM REDUTORA 2" },
  { channel: "2.4.54", description: "GB2 CLTCH EN/DISENG", translation: "ENGRAZAMENTO / DESENGRAZAMENTO DA ENGRENAGEM REDUTORA 2" },
  { channel: "2.4.55", description: "GB2 T-GEAR EN/DISENG", translation: "ENGRENAGEM GIRATÓRIA / DESENGRAZAMENTO DA ENGRENAGEM REDUTORA 2" },
  { channel: "2.4.56", description: "GB2 SHFT BRK ON-OFF", translation: "INDICAÇÃO DO FREIO DO EIXO LIGADO / DESLIGADO DA ENGRENAGEM REDUTORA 2" },
  { channel: "2.4.57", description: "GB2 SHFT LOCK ON.OFF", translation: "TRAVAMENTO DO EIXO LIGADO / DESLIGADO DA ENGRENAGEM REDUTORA 2" },
  { channel: "2.4.58", description: "CWU PUMP4 DISCH PR", translation: "PRESSÃO DE DESCARGA DA BOMBA DA URA 4" },
  { channel: "2.4.59", description: "CWU PUMP5 DISCH PR", translation: "PRESSÃO DE DESCARGA DA BOMBA DA URA 5" },
  { channel: "2.4.60", description: "CWU PUMP6 DISCH PR", translation: "PRESSÃO DE DESCARGA DA BOMBA DA URA 6" },
  { channel: "2.4.61", description: "CWU NO4 TEMP", translation: "TEMPERATURA DA URA 4" },
  { channel: "2.4.62", description: "CWU NO5 TEMP HIGH", translation: "TEMPERATURA DA URA 5" },
  { channel: "2.4.63", description: "CWU NO6 TEMP", translation: "TEMPERATURA DA URA 6" },
  { channel: "2.4.64", description: "GB2 SHFT BRK PWR FAIL", translation: "FALHA NA ALIMENTAÇÃO DO FREIO DO EIXO DA ENGRENAGEM REDUTORA 2" },

  // --- 2.5.XX: BRG TEMPS, POWER AR E STEERING ---
  { channel: "2.5.01", description: "SHAFT BRG6 STBD TEMP", translation: "TEMPERATURA DO MANCAL 6 DO EIXO DE BORESTE" },
  { channel: "2.5.02", description: "SHAFT BRG7 STBD TEMP", translation: "TEMPERATURA DO MANCAL 7 DO EIXO DE BORESTE" },
  { channel: "2.5.03", description: "SHAFT BRG9 PORT TEMP", translation: "TEMPERATURA DO MANCAL 9 DO EIXO DE BOMBORDO" },
  { channel: "2.5.04", description: "SHAFT BRG10 PT TEMP", translation: "TEMPERATURA DO MANCAL 10 DO EIXO DE BOMBORDO" },
  { channel: "2.5.05", description: "DOMESTIC PROV PLANT", translation: "PLANTA DOMESTICA DE PROVISÕES (PRONTO USO)" },
  { channel: "2.5.07", description: "A STP STBD BILGE HI", translation: "NIVEL ALTO DO POCETO DO EIXO DE BORESTE MAIS AR" },
  { channel: "2.5.08", description: "PAFT SWG RM BILGE HI", translation: "NIVEL ALTO DO POCETO MAIS AR DE BOMBORDO DO COMPARTIMENTO 9N" },
  { channel: "2.5.09", description: "SAFT PP RM BILGE HI", translation: "NIVEL ALTO DO POCETO MAIS AR DE BORESTE DA BOMBA NO COMPARTIMENTO 9N" },
  { channel: "2.5.10", description: "PT AFT PPRM BILGE HI", translation: "NIVEL ALTO DO POCETO MAIS AR DE BOMBORDO DA BOMBA NO COMPARTIMENTO 9N" },
  { channel: "2.5.11", description: "STG RM PORT 7DK HI", translation: "NIVEL ALTO DO PAIOL DO PISO 7" },
  { channel: "2.5.13", description: "AMSB A1 VOLTS LOW", translation: "BAIXA TENSÃO NO BARRAMENTO A1" },
  { channel: "2.5.14", description: "AMSB A1 VOLTS HIGH", translation: "ALTA TENSÃO NO BARRAMENTO A1" },
  { channel: "2.5.15", description: "AMSB A1 FREQ LOW", translation: "BAIXA FREQUENCIA NO BARRAMENTO A1" },
  { channel: "2.5.16", description: "AMSB A1 FREQ HIGH", translation: "ALTA FREQUENCIA NO BARRAMENTO A1" },
  { channel: "2.5.17", description: "AMSB A1 PREF TRIP PW", translation: "PREFERENCIAL TRIPPED DO BARRAMENTO A1" },
  { channel: "2.5.18", description: "AMSB A1. A2 PREF TRIP", translation: "PREFERENCIAL TRIPPED DO BARRAMENTO A1 E A2" },
  { channel: "2.5.19", description: "ASB SH TRIP PWR FAIL", translation: "FALHA DE ALIMENTAÇÃO DO INTERCONECTOR DO BARRAMENTO AV" },
  { channel: "2.5.20", description: "AMSB A2 VOLTS LOW", translation: "BAIXA TENSÃO NO BARRAMENTO A2" },
  { channel: "2.5.21", description: "AMSB A2 VOLTS HIGH", translation: "ALTA TENSÃO NO BARRAMENTO A2" },
  { channel: "2.5.22", description: "AMSB A2 FREQ LOW", translation: "BAIXA FREQUENCIA NO BARRAMENTO A2" },
  { channel: "2.5.23", description: "AMSB A2 FREQ HIGH", translation: "ALTA FREQUENCIA NO BARRAMENTO A2" },
  { channel: "2.5.24", description: "AMSB A2 PREF TRIP PW", translation: "PREFERENCIAL TRIPPED DO BARRAMENTO A2" },
  { channel: "2.5.25", description: "STEER GR STBD FAULT", translation: "FALHA NA MAQUINA DO LEME DE BORESTE" },
  { channel: "2.5.26", description: "COLD FW PUMP3 PRESS", translation: "PRESSAO DA BOMBA 3 DE AGUA POTAVEL" },
  { channel: "2.5.27", description: "COLD FW PUMP4 PRESS", translation: "PRESSAO DA BOMBA 4 DE AGUA POTAVEL" },
  { channel: "2.5.28", description: "HELI PP1 FUEL TEMP H", translation: "ALTA TEMPERATURA DA BOMBA 1 DE AVCAT" },
  { channel: "2.5.29", description: "HELI PP2 FUEL TEMP H", translation: "ALTA TEMPERATURA DA BOMBA 2 DE AVCAT" },
  { channel: "2.5.30", description: "SHFT TUNNEL BILGE HI", translation: "NIVEL ALTO DO POCETO DO TUBO DO EIXO" },
  { channel: "2.5.32", description: "SEWAGE PLANT4 HI", translation: "NIVEL ALTO DA PLANTA 4 DE ESGOTO" },
  { channel: "2.5.33", description: "HYD PK4 RE OP VALVES", translation: "OPERAÇÃO DA VALVULA HIDRAULICA DO PACOTE 4 DA PRAÇA DE MAQUINA" },
  { channel: "2.5.34", description: "SKEG BILGE FR 242 HI", translation: "NIVEL ALTO POCETO DA CAVERNA 242" },
  { channel: "2.5.36", description: "AFT DRAUGHT IND", translation: "INDICAÇÃO DO LASTRO AR" },
  { channel: "2.5.37", description: "AMSB A1 REVERSE PWR", translation: "POTENCIA REVERSA NO BARRAMENTO A1" },
  { channel: "2.5.38", description: "AMSB A1 OVERCURRENT", translation: "ALTA CORRENTE NO BARRAMENTO A1" },
  { channel: "2.5.39", description: "AMSB A1 SHORT CIRC", translation: "CURTO CIRCUITO NO BARRAMENTO A1" },
  { channel: "2.5.40", description: "AMSB A2 REVERSE PWR", translation: "POTENCIA REVERSA NO BARRAMENTO A2" },
  { channel: "2.5.41", description: "AMSB A2 OVERCURRENT", translation: "ALTA CORRENTE NO BARRAMENTO A2" },
  { channel: "2.5.42", description: "AMSB A1 SHORT CIRCUIT", translation: "CURTO CIRCUITO NO BARRAMENTO A2" },
  { channel: "2.5.43", description: "9N GREY WTR TNK HIGH", translation: "NIVEL ALTO DO TANQUE DE AGUAS CINZAS 9N" },
  { channel: "2.5.44", description: "GYROB-DDUB FAILURE", translation: "FALHA NA GIRO B E DDU B" },
  { channel: "2.5.45", description: "DDUB MAINT WARNING", translation: "AVISO DE MANUTENÇÃO DA DDU B" },
  { channel: "2.5.46", description: "24VDC SUBSTATION 6MZ", translation: "TRU 6M" },
  { channel: "2.5.47", description: "STEER GR PORT FAULT", translation: "FALHA NA MAQUINA DO LEME DE BOMBORDO" },
  { channel: "2.5.48", description: "DEEP FAT FRYER OVRHT", translation: "SUPERAQUECIMENTO DA FRITADEIRA" },
  { channel: "2.5.49", description: "GALLEY SUPPLIES ON", translation: "ALIMENTAÇÃO DA COZINHA" },
  { channel: "2.5.55", description: "18-TK HI SUC VV OPEN", translation: "ABERTURA DA VÁLVULA SUPERIOR DE SUCÇÃO DO TANQUE 18" },
  { channel: "2.5.56", description: "18-TK HI SUC VV SHUT", translation: "FECHAMENTO DA VÁLVULA SUPERIOR DE SUCÇÃO DO TANQUE 18" },
  { channel: "2.5.57", description: "18-TK LO SUC VV OPEN", translation: "ABERTURA DA VÁLVULA INFERIOR DE SUCÇÃO DO TANQUE 18" },
  { channel: "2.5.58", description: "18-TK LO SUC VV SHUT", translation: "FECHAMENTO DA VÁLVULA INFERIOR DE SUCÇÃO DO TANQUE 18" },
  { channel: "2.5.59", description: "19-TK HI SUC VV OPEN", translation: "ABERTURA DA VÁLVULA SUPERIOR DE SUCÇÃO DO TANQUE 19" },
  { channel: "2.5.60", description: "19-TK HI SUC VV SHUT", translation: "FECHAMENTO DA VÁLVULA SUPERIOR DE SUCÇÃO DO TANQUE 19" },
  { channel: "2.5.61", description: "19-TK LO SUC VV OPEN", translation: "ABERTURA DA VÁLVULA INFERIOR DE SUCÇÃO DO TANQUE 19" },
  { channel: "2.5.62", description: "19-TK LO SUC VV SHUT", translation: "FECHAMENTO DA VÁLVULA INFERIOR DE SUCÇÃO DO TANQUE 19" },
  { channel: "2.5.63", description: "STB STERN SEAL FLOW", translation: "FLUXO DA AGUA DE REFRIAMENTO DO SELO DO EIXO BORESTE" },
  { channel: "2.5.64", description: "PORT STER SEAL FLOW", translation: "FLUXO DA AGUA DE REFRIAMENTO DO SELO DO EIXO BOMBORDO" },

  // --- 2.6.XX: PLANTAS FRIGORÍFICAS E AUX AR ---
  { channel: "2.6.01", description: "MEAT STORE 7QA4 TEMP", translation: "TEMPERATURA DA FRIGORIFICA DE CARNE 7QA4" },
  { channel: "2.6.02", description: "DAIRY STORE TEMP HI", translation: "TEMPERATURA DO PAIOL DE PRONTO USO" },
  { channel: "2.6.03", description: "FRUIT-VEG STORE T HI", translation: "TEMPERATURA DA FRIGORIFICA DE FRUTAS E VEGETAIS" },
  { channel: "2.6.04", description: "COLD ROOM 2", translation: "FRIGORIFICA 2" },
  { channel: "2.6.05", description: "FLOUR STORE TEMP HI", translation: "TEMPERATURA DO PAIOL DE FARINHA" },
  { channel: "2.6.06", description: "DG3 CYL 1A EXH TEMP", translation: "TEMPERATURA DE DESCARGA DO CILINDRO 1A DO MCA 3" },
  { channel: "2.6.07", description: "DG3 A2 CYL TEMP", translation: "TEMPERATURA DE DESCARGA DO CILINDRO 2A DO MCA 3" },
  { channel: "2.6.08", description: "DG3 CYL A3 EXH TEMP", translation: "TEMPERATURA DE DESCARGA DO CILINDRO 3A DO MCA 3" },
  { channel: "2.6.09", description: "DG3 CYL 4A EXH TEMP", translation: "TEMPERATURA DE DESCARGA DO CILINDRO 4A DO MCA 3" },
  { channel: "2.6.10", description: "DG3 CYL 5A EXH TEMP", translation: "TEMPERATURA DE DESCARGA DO CILINDRO 5A DO MCA 3" },
  { channel: "2.6.11", description: "DG3 CYL 6A EXH TEMP", translation: "TEMPERATURA DE DESCARGA DO CILINDRO 6A DO MCA 3" },
  { channel: "2.6.12", description: "DG3 CYL 1B EXH TEMP", translation: "TEMPERATURA DE DESCARGA DO CILINDRO 1B DO MCA 3" },
  { channel: "2.6.13", description: "DG3 CYL 2B EXH TEMP", translation: "TEMPERATURA DE DESCARGA DO CILINDRO 2B DO MCA 3" },
  { channel: "2.6.14", description: "DG3 CYL 3B EXH TEMP", translation: "TEMPERATURA DE DESCARGA DO CILINDRO 3B DO MCA 3" },
  { channel: "2.6.15", description: "DG3 CYL 4B EXH TEMP", translation: "TEMPERATURA DE DESCARGA DO CILINDRO 4B DO MCA 3" },
  { channel: "2.6.16", description: "DG3 CYL 5B EXH TEMP", translation: "TEMPERATURA DE DESCARGA DO CILINDRO 5B DO MCA 3" },
  { channel: "2.6.17", description: "DG3 CYL 6B EXH TEMP", translation: "TEMPERATURA DE DESCARGA DO CILINDRO 6B DO MCA 3" },
  { channel: "2.6.18", description: "DG3 EXH GAS AVERAGE", translation: "MÉDIA DAS DESCARGAS DOS GASES DO MCA 3" },
  { channel: "2.6.19", description: "DG3 EXH DEVIATION", translation: "DESVIO DA DESCARGA DO MCA 3" },
  { channel: "2.6.20", description: "DG4 CYL 1A EXH TEMP", translation: "TEMPERATURA DE DESCARGA DO CILINDRO 1A DO MCA 4" },
  { channel: "2.6.21", description: "DG4 CYL 2A EXH TEMP", translation: "TEMPERATURA DE DESCARGA DO CILINDRO 2A DO MCA 4" },
  { channel: "2.6.22", description: "DG4 CYL 3A EXH TEMP", translation: "TEMPERATURA DE DESCARGA DO CILINDRO 3A DO MCA 4" },
  { channel: "2.6.23", description: "DG4 CYL 4A EXH TEMP", translation: "TEMPERATURA DE DESCARGA DO CILINDRO 4A DO MCA 4" },
  { channel: "2.6.24", description: "DG4 CYL 5A EXH TEMP", translation: "TEMPERATURA DE DESCARGA DO CILINDRO 5A DO MCA 4" },
  { channel: "2.6.25", description: "DG4 CYL 6A EXH TEMP", translation: "TEMPERATURA DE DESCARGA DO CILINDRO 6A DO MCA 4" },
  { channel: "2.6.26", description: "DG4 CYL 1B EXH TEMP", translation: "TEMPERATURA DE DESCARGA DO CILINDRO 1B DO MCA 4" },
  { channel: "2.6.27", description: "DG4 CYL 2B EXH TEMP", translation: "TEMPERATURA DE DESCARGA DO CILINDRO 2B DO MCA 4" },
  { channel: "2.6.28", description: "DG4 CYL 3B EXH TEMP", translation: "TEMPERATURA DE DESCARGA DO CILINDRO 3B DO MCA 4" },
  { channel: "2.6.29", description: "DG4 CYL 4B EXH TEMP", translation: "TEMPERATURA DE DESCARGA DO CILINDRO 4B DO MCA 4" },
  { channel: "2.6.30", description: "DG4 CYL 5B EXH TEMP", translation: "TEMPERATURA DE DESCARGA DO CILINDRO 5B DO MCA 4" },
  { channel: "2.6.31", description: "DG4 CYL 6B EXH TEMP", translation: "TEMPERATURA DE DESCARGA DO CILINDRO 6B DO MCA 4" },
  { channel: "2.6.32", description: "DG4 EXH GAS AVERAGE", translation: "MÉDIA DAS DESCARGAS DOS GASES DO MCA 4" },
  { channel: "2.6.33", description: "DG4 EXH DEVIATION", translation: "DESVIO DA DESCARGA DO MCA 4" },
  { channel: "2.6.34", description: "AFT CFW HI PT PRESS", translation: "INDICAÇÃO DE PRESSÃO DA AGUA GELADA AR" },
  { channel: "2.6.35", description: "AVCAT TRANS PP1 RUN", translation: "BOMBA DE TRANSFERENCIA DE AVCAT 1 EM FUNCIONAMENTO" },
  { channel: "2.6.36", description: "AVCAT HELI F PP1 RUN", translation: "BOMBA DE AVCAT 1 EM FUNCIONAMENTO – HELI F" },
  { channel: "2.6.37", description: "AVCAT VEHIC PP1 RUN", translation: "BOMBA DE AVCAT 1 EM FUNCIONAMENTO – VEHIC" },
  { channel: "2.6.38", description: "AVCAT TRANS PP2 RUN", translation: "BOMBA DE TRANSFERENCIA DE AVCAT 2 EM FUNCIONAMENTO" },
  { channel: "2.6.39", description: "AVCAT HELI F PP2 RUN", translation: "BOMBA DE AVCAT 2 EM FUNCIONAMENTO – HELI F" },
  { channel: "2.6.40", description: "AVCAT VEH PP2 RUN", translation: "BOMBA DE AVCAT 2 EM FUNCIONAMENTO – VEHIC" },
  { channel: "2.6.41", description: "AME OIL MIST D DTR1", translation: "DENSIDADE DA SUJIDADE DA NÉVOA DE ÓLEO 1 DO MCP AR" },
  { channel: "2.6.42", description: "AME OIL MIST D DTR2", translation: "DENSIDADE DA SUJIDADE DA NÉVOA DE ÓLEO 2 DO MCP AR" },
  { channel: "2.6.43", description: "AME OIL MIST D DTR3", translation: "DENSIDADE DA SUJIDADE DA NÉVOA DE ÓLEO 3 DO MCP AR" },
  { channel: "2.6.44", description: "AME OIL MIST D DTR4", translation: "DENSIDADE DA SUJIDADE DA NÉVOA DE ÓLEO 4 DO MCP AR" },
  { channel: "2.6.45", description: "AME OIL MIST D DTR5", translation: "DENSIDADE DA SUJIDADE DA NÉVOA DE ÓLEO 5 DO MCP AR" },
  { channel: "2.6.46", description: "AME OIL MIST D DTR6", translation: "DENSIDADE DA SUJIDADE DA NÉVOA DE ÓLEO 6 DO MCP AR" },
  { channel: "2.6.47", description: "MEAT STORE 7QZ2 TEMP", translation: "TEMPERATURA DA FRIGORIFICA DE CARNE 7QZ2" },
  { channel: "2.6.49", description: "LP AIR COMP3 RUNNING", translation: "COMPRESSOR DE BAIXA PRESSÃO DE AR 3 EM FUNCIONAMENTO" },
  { channel: "2.6.50", description: "LP AIR COMP3 TRIPPED", translation: "COMPRESSOR DE BAIXA PRESSÃO DE AR 3 FALHA OU DESLIGADO" },
  { channel: "2.6.51", description: "LP AIR COMP4 RUNNING", translation: "COMPRESSOR DE BAIXA PRESSÃO DE AR 4 EM FUNCIONAMENTO" },
  { channel: "2.6.52", description: "LP AIR COMP4 TRIPPED", translation: "COMPRESSOR DE BAIXA PRESSÃO DE AR 4 FALHA OU DESLIGADO" }
];

export const SHIP_CONFIG = {
  name: "NAM ATLÂNTICO",
  hullNumber: "A140",
  designation: "Navio-Aeródromo Multipropósito",
  badgeUrl: "https://forcaaerea.com.br/wp-content/uploads/2020/11/A140_NAM_ATLANTICO_PHM.jpg"
};
